import type { Article } from "../types";

export const MAY_2026: Article[] = [
  {
    id: "ns-2026-05-india-heat-power-demand",
    slug: "may-2026-heat-forecast-and-record-power-demand",
    type: "analysis",
    category: "lifestyle",
    tags: ["IMD", "heatwave", "power demand", "peak load", "households"],
    kicker: "Analysis",
    headline:
      "May's heat arrived on schedule, and the grid said exactly how hot it was",
    dek: "The meteorological department's May outlook promised more heatwave days and hotter nights. Three weeks later the national power peak had set an all-time record. This is what a hot month costs an ordinary household.",
    dateline: "Bengaluru",
    publishedAt: "2026-05-22T05:10:00.000Z",
    updatedAt: "2026-05-26T06:40:00.000Z",
    authorId: "a-ashwin-jois",
    keyPoints: [
      "IMD's May outlook, published on May 1, forecast more heatwave days and above-normal night temperatures in parts of India.",
      "National peak power demand crossed 260 GW for the first time on May 19, set a record 265.44 GW on May 20 and an all-time high of 270.82 GW on May 21.",
      "A record load is a systems number. What households feel is the bill, the outage risk and the night that will not cool down.",
    ],
    flags: { editorsPick: true },
    body: [
      {
        kind: "para",
        text: "The most useful thing the India Meteorological Department said about May was published on the first day of the month, and it was not reassuring. The outlook carried two distinct warnings: more heatwave days across several regions, and night temperatures running above normal in parts of the country. Both matter, and they are not the same problem.",
      },
      {
        kind: "para",
        text: "A hot afternoon is a scheduling inconvenience. A hot night is a physiological one, because the body sheds heat overnight and buildings designed for a milder climate hold warmth long after the sun is down. When a forecast flags nights separately, it is telling you which of the two is in play.",
      },
      { kind: "subhead", text: "What the load figures actually record" },
      {
        kind: "para",
        text: "Electricity demand is the closest thing India has to a real-time thermometer for the whole country, because almost every degree of cooling demand becomes load rather than a private choice. National peak demand crossed 260 GW for the first time on May 19, set a record 265.44 GW the next day, and reached an all-time high of 270.82 GW on May 21. Three records in three days is the shape of a sustained event, not a one-off spike.",
      },
      {
        kind: "numberline",
        items: [
          "May 1: IMD outlook flags more heatwave days and above-normal night temperatures.",
          "May 19: national peak power demand crosses 260 GW for the first time.",
          "May 20: peak demand sets a record 265.44 GW.",
          "May 21: peak demand reaches an all-time high of 270.82 GW.",
        ],
      },
      {
        kind: "para",
        text: "None of those figures is a projection. They are meter readings, and they describe a system that absorbed them. That is the part of the story that deserves more attention than the headline suggests: a record is only remarkable if the previous one was missed by something embarrassing.",
      },
      { kind: "subhead", text: "Where this lands at home" },
      {
        kind: "para",
        text: "The household version of a record load is duller and more consequential. It is the ceiling fan competing with the refrigerator, the water pump running at the same hour as everyone else's, and the inverter battery standing between a fan and a dark room during an interruption. It is also why fuel and power prices moved in the same fortnight for entirely unrelated reasons, and why a hot month is an economic event rather than a weather report.",
      },
      {
        kind: "callout",
        title: "The two numbers to keep apart",
        text: "Peak demand measures the maximum the system was asked to carry. It says nothing about whether households received reliable supply while it did so. Treating the record as a success would credit the grid for a demand peak and ignore the outages, voltage dips and scheduled rotation underneath it.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: retrospective analysis assembled by NOT SCRIPTED from the India Meteorological Department's May outlook as reported by Deccan Herald on May 1 and from Deccan Herald's reporting on national peak power demand on May 19, 20 and 21, 2026. World Weather Attribution's pre-monsoon heat assessment is cited as independent context. No interviews were conducted and no site visit was made.",
      },
    ],
    sources: [
      {
        name: "Deccan Herald — India",
        url: "https://www.deccanherald.com/india/imd-forecasts-more-heatwave-days-warmer-nights-likely-in-some-parts-of-india-in-may-3987766",
        date: "2026-05-01",
        type: "publication",
      },
      {
        name: "Deccan Herald — India",
        url: "https://www.deccanherald.com/india/peak-power-demand-of-india-crosses-260-gw-for-first-time-as-heatwave-intensifies-across-several-regions-4008992",
        date: "2026-05-19",
        type: "publication",
      },
      {
        name: "Deccan Herald — India",
        url: "https://www.deccanherald.com/india/indias-peak-power-demand-hits-record-26544-gw-amid-severe-heatwave-4010256",
        date: "2026-05-20",
        type: "publication",
      },
      {
        name: "Deccan Herald — India",
        url: "https://www.deccanherald.com/india/indias-peak-power-demand-hits-all-time-high-of-27082-gw-amid-heatwave-4011685",
        date: "2026-05-21",
        type: "publication",
      },
      {
        name: "World Weather Attribution",
        url: "https://www.worldweatherattribution.org/climate-change-exposes-hundreds-of-millions-to-longer-and-deadlier-pre-monsoon-heat-in-south-asia/",
        type: "research",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: concentric arcs of a heat map over a stylised load-curve graph, warm amber and rust tones fading into a deep blue band at the base.",
      caption: "India's national peak power demand set three records in three days during a May 2026 heat event.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-assembly-verdicts-analysis",
    slug: "five-states-three-governments-after-2026-verdicts",
    type: "analysis",
    category: "politics",
    tags: ["assembly elections", "West Bengal", "Tamil Nadu", "Kerala", "coalitions"],
    kicker: "Analysis",
    headline:
      "Five states, three new governments, and one question nobody has answered",
    dek: "The BJP breached West Bengal and a new formation took Tamil Nadu. The interesting part of this election cycle is not who won. It is how many governments are now running without a settled majority.",
    dateline: "New Delhi",
    publishedAt: "2026-05-05T03:40:00.000Z",
    updatedAt: "2026-05-12T07:20:00.000Z",
    authorId: "a-meera-iyengar",
    keyPoints: [
      "Results counted on May 4 saw the BJP breach West Bengal, a TVK-led formation take Tamil Nadu, and Congress win Kerala despite its INDIA bloc partners losing elsewhere.",
      "By May 9 AMMK chief T V V Dhinakaran had asked the Governor to invite the AIADMK to form a government in Tamil Nadu, alleging horse-trading.",
      "Congress was still publicly undecided on its Kerala chief ministerial choice on May 10.",
    ],
    flags: { topStory: true },
    body: [
      {
        kind: "para",
        text: "When results were counted on May 4, the headline was a breach. The BJP crossed from a distant third to governing party in West Bengal for the first time in the state's history, and Tamil Nadu produced a government in which a political formation barely two years old holds the balance of power. Neither outcome surprised people who had been counting booth-level swings rather than opinion polls.",
      },
      {
        kind: "para",
        text: "The genuinely novel fact was elsewhere. Congress won Kerala while its INDIA bloc partners lost ground in West Bengal and Tamil Nadu. The alliance assembled to defeat the BJP in 2024 has now shown that its parts do not travel well without each other, and that a national umbrella is not a substitute for a state organisation.",
      },
      { kind: "subhead", text: "Three governments, no settled majority" },
      {
        kind: "para",
        text: "The question of chief ministers in Kerala, West Bengal, Tamil Nadu, Assam and Puducherry took more than a day to resolve, which is itself the finding. In Tamil Nadu the contest was not merely between parties but over who could assemble a floor, and by May 9 that had become concrete enough for the AMMK chief T V V Dhinakaran to ask the Governor to invite the AIADMK to form a government, alleging horse-trading. In Kerala, Congress was still publicly undecided on its choice on May 10.",
      },
      {
        kind: "bullets",
        items: [
          "West Bengal: the BJP governing the state for the first time, after a campaign fought largely on electoral rolls and citizenship.",
          "Tamil Nadu: a young formation in government, with analysts describing the DMK as flexible and the Opposition unusually weak.",
          "Kerala: a Congress win its own bloc partners did not match, with the chief ministerial decision outstanding a week after the count.",
        ],
      },
      {
        kind: "para",
        text: "What makes this cycle unusual is not instability as such. Indian state governments have been unstable before. It is that the sources of instability have moved: from defections inside one party to arithmetic that spans parties, regions and, in one telling case, a candidate's film career.",
      },
      {
        kind: "callout",
        title: "What the verdicts did not settle",
        text: "None of these assemblies produced a governing majority on its own. Every new administration began its life needing partners, which turns routine administration into a monthly negotiation and puts arithmetic, not a policy platform, at the centre of government.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: NOT SCRIPTED compiled this analysis from Deccan Herald's election coverage published on May 4, 5, 9 and 10, 2026 and from Indian Express political reporting of May 12. It is retrospective interpretation written after the count, not a prediction made on the night of the result.",
      },
    ],
    sources: [
      {
        name: "Deccan Herald — Elections",
        url: "https://www.deccanherald.com/elections/india/assembly-elections-results-2026-bjp-breaches-west-bengal-tamil-nadu-gets-a-jana-nayagan-3991213",
        date: "2026-05-04",
        type: "publication",
      },
      {
        name: "Deccan Herald — Elections",
        url: "https://www.deccanherald.com/elections/india/assembly-elections-2026-kerala-win-boosts-congress-despite-india-bloc-allies-loss-in-west-bengal-tamil-nadu-3990642",
        date: "2026-05-04",
        type: "publication",
      },
      {
        name: "Deccan Herald — India",
        url: "https://www.deccanherald.com/india/assembly-elections-2026-who-will-be-next-cms-in-kerala-west-bengal-tamil-nadu-assam-and-puducherry-3991532",
        date: "2026-05-05",
        type: "publication",
      },
      {
        name: "Deccan Herald — Elections",
        url: "https://www.deccanherald.com/elections/tamil-nadu/tamil-nadu-assembly-election-results-2026-ammk-chief-t-v-v-dhinakaran-asks-the-governor-to-invite-aiadmk-alleges-horse-trading-3996667",
        date: "2026-05-09",
        type: "publication",
      },
      {
        name: "Deccan Herald — Elections",
        url: "https://www.deccanherald.com/elections/kerala/kerala-assembly-elections-results-2026-congress-says-final-call-on-cm-to-come-in-due-course-3997357",
        date: "2026-05-10",
        type: "publication",
      },
      {
        name: "Indian Express — Political Pulse",
        url: "https://indianexpress.com/article/political-pulse/in-tamil-nadu-flux-bjp-spots-an-opening-flexible-dmk-weaker-opposition-10685263/",
        date: "2026-05-12",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: five tall vertical bars of differing heights in a row, two leaning against each other, set against a gridded results backdrop in deep maroon and cream.",
      caption: "Five assemblies were counted in May 2026; three produced governments without a clear governing majority.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-so2-coal-plant-deaths",
    slug: "coal-plant-so2-emissions-deaths-iit-delhi-study",
    type: "explainer",
    category: "science",
    tags: ["air pollution", "sulphur dioxide", "coal power", "mortality", "IIT Delhi"],
    kicker: "Explainer",
    headline:
      "1.24 lakh deaths a year, one pollutant, one lever: what the SO2 study means",
    dek: "An IIT Delhi study puts a number on something Indian air-quality policy has argued about for two decades. The figure is large, the mechanism is unglamorous, and the intervention is largely settled.",
    dateline: "New Delhi",
    publishedAt: "2026-05-07T02:20:00.000Z",
    authorId: "a-nadia-rahman",
    keyPoints: [
      "A study from IIT Delhi estimates that curbing sulphur dioxide emissions from coal power plants could prevent more than 1.24 lakh deaths a year in India.",
      "SO2 is measured on the same network that produces the air quality index, but it does not drive the headline number the way fine particulate pollution does.",
      "Delhi's dashboard in early May showed ozone rising while nitrogen dioxide and carbon monoxide fell, an inversion that complicates the standard clean-air narrative.",
    ],
    flags: { mostRead: true },
    body: [
      {
        kind: "para",
        text: "Indian air-quality policy has spent fifteen years arguing about particles. That was a reasonable focus, because fine particulate matter has the clearest dose-response curve and the most legible public health case. But it left a second pollutant in an awkward position. Sulphur dioxide is measured continuously, it is regulated on paper, and the control technology for it has existed for far longer than the current debate.",
      },
      {
        kind: "para",
        text: "That is the gap a study from IIT Delhi attempted to close in early May 2026. Its estimate is stark: curbing sulphur dioxide emissions from coal power plants could prevent more than 1.24 lakh deaths a year in India. That is not a projection of harm avoided in future. It is an accounting of harm currently occurring.",
      },
      { kind: "subhead", text: "Why SO2 keeps getting lost" },
      {
        kind: "para",
        text: "Two reasons. The first is that the index newspapers quote is dominated by particulate matter and ozone, so a city can improve its headline number while its sulphur dioxide load tells a different story. The second is that SO2 converts to sulphate aerosol close to its source, which makes it a regional problem rather than a purely local one. A plant hundreds of kilometres away can be part of what a city breathes.",
      },
      {
        kind: "para",
        text: "Delhi's own readings in early May illustrated the problem in miniature. The city's air quality dashboard showed ozone rising while nitrogen dioxide and carbon monoxide declined, Indian Express reported on May 6. Ozone is not emitted at the tailpipe; it forms in sunlight from other pollutants. A shift in the mix is exactly the situation in which a single headline number stops being informative.",
      },
      {
        kind: "bullets",
        items: [
          "The study's estimate: more than 1.24 lakh deaths a year attributable to sulphur dioxide emissions from coal power plants.",
          "The instrument: continuous SO2 monitoring on the national station network, which is what makes an attribution estimate possible at all.",
          "The control: emission limits applied at the source, which is an engineering problem rather than a behavioural one.",
        ],
      },
      {
        kind: "para",
        text: "What the study does not do is say how quickly any of this changes. Sulphur limits in India have moved in steps, and plants need capital rather than announcements. The fair reading is that the number establishes the size of the prize, not the timeline for collecting it.",
      },
      {
        kind: "callout",
        title: "How to read the 1.24 lakh figure",
        text: "Attribution estimates of this kind are model output, not a counted list of names. They describe a population of deaths that would not have occurred under a counterfactual of lower emissions, which is why the figure is best used for ranking interventions rather than for stating a precise toll.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this explainer was written retrospectively by NOT SCRIPTED from Indian Express coverage of the IIT Delhi study published on May 7, 2026, Indian Express coverage of Delhi's air quality dashboard published on May 6, and the Central Pollution Control Board's published air quality reporting. NOT SCRIPTED has not reviewed the underlying study document and does not restate its methodology beyond the cited coverage.",
      },
    ],
    sources: [
      {
        name: "Indian Express — Delhi",
        url: "https://indianexpress.com/article/cities/delhi/mitigating-so2-from-coal-power-plants-could-prevent-over-1-24-lakh-deaths-annually-in-india-says-iit-delhi-study-10676757/",
        date: "2026-05-07",
        type: "publication",
      },
      {
        name: "Indian Express — Delhi",
        url: "https://indianexpress.com/article/cities/delhi/pollution-shift-delhis-air-quality-dashboard-shows-rise-in-ozone-as-no2-co-decline-10674852/",
        date: "2026-05-06",
        type: "publication",
      },
      {
        name: "Central Pollution Control Board",
        url: "https://cpcb.nic.in/National_Air_Quality_Index/",
        type: "official",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a tall chimney rendered as a thin teal line releasing layered translucent bands that disperse into a field of small measured squares arranged like a monitoring grid.",
      caption: "Continuous sulphur dioxide monitoring is what allows mortality to be attributed to coal-plant emissions rather than guessed at.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-karnataka-hijab-order",
    slug: "karnataka-withdraws-2022-hijab-classroom-order",
    type: "news-update",
    category: "karnataka",
    tags: ["Karnataka", "hijab", "schools", "education policy", "minority rights"],
    kicker: "Bengaluru & Karnataka",
    headline: "Karnataka withdraws its 2022 order barring hijab in classrooms",
    dek: "The state government has formally rolled back the instruction it issued in September 2022. The decision drew immediate criticism from the ruling party that introduced it and renewed protests from the organisations that opposed it.",
    dateline: "Bengaluru",
    publishedAt: "2026-05-13T06:30:00.000Z",
    updatedAt: "2026-05-15T04:10:00.000Z",
    authorId: "a-imran-khan",
    keyPoints: [
      "Karnataka has rolled back the September 2022 instruction that barred the hijab in classrooms, Deccan Herald reported on May 13.",
      "Union minister Pralhad Joshi said on May 14 that the Congress move lifting the ban disrespects the judicial process.",
      "Organisations that had opposed the 2022 order said they would continue their protest campaign.",
    ],
    body: [
      {
        kind: "para",
        text: "The Karnataka government has withdrawn the instruction it issued in September 2022 directing schools in the state to bar the hijab in classrooms. Deccan Herald reported the rollback on May 13, describing it as the reversal of one of the most contested administrative orders of the previous government in the state.",
      },
      {
        kind: "para",
        text: "The order was framed at the time as a uniform dress code rather than a religious restriction, and that distinction was contested for its entire duration. Students and families challenged it in court, and the debate spread well beyond Karnataka into national politics.",
      },
      { kind: "subhead", text: "The reaction" },
      {
        kind: "para",
        text: "The criticism came immediately and from an unusual direction. Union minister Pralhad Joshi, a BJP leader from Maharashtra, said on May 14 that the Congress move lifting the ban in Karnataka schools disrespects the judicial process. On the other side, organisations that had opposed the 2022 instruction said they would keep up their agitation against the reversal.",
      },
      {
        kind: "para",
        text: "Both reactions point at the same unresolved thing. An administrative order governing what students wear in a classroom sat in a category that blurred education policy, religious practice and the limits of what a state may regulate. Withdrawing it returns the question to the states rather than settling it, and the litigation that followed the 2022 order does not disappear because the instruction has been cancelled.",
      },
      {
        kind: "callout",
        title: "A cancellation is not a resolution",
        text: "Withdrawing an instruction reverses a policy. It does not answer the underlying question of who decides student dress in a state-run school, which is a question the courts were asked and have not yet answered.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Deccan Herald's Karnataka coverage of May 13, 14 and 21, 2026. NOT SCRIPTED has not spoken to the state education department, to the affected schools or to the organisations named in this report.",
      },
    ],
    sources: [
      {
        name: "Deccan Herald — Karnataka",
        url: "https://www.deccanherald.com/india/karnataka/karnataka-rolls-back-2022-order-banning-hijab-in-classrooms-4001887",
        date: "2026-05-13",
        type: "publication",
      },
      {
        name: "Deccan Herald — Karnataka",
        url: "https://www.deccanherald.com/india/karnataka/karnataka-govt-withdraws-bjp-era-2022-order-banning-hijab-in-classrooms-4001501",
        date: "2026-05-13",
        type: "publication",
      },
      {
        name: "Deccan Herald — Karnataka",
        url: "https://www.deccanherald.com/india/karnataka/disrespect-to-judicial-process-pralhad-joshi-slams-congress-for-lifting-hijab-ban-in-karnataka-schools-4002680",
        date: "2026-05-14",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: an official-looking sheet rendered in rust and cream, half of it dissolving into soft fabric-like folds, framed by two flat vertical colour fields meeting at a hard edge.",
      caption: "A four-year-old administrative order over classroom dress has been formally withdrawn in Karnataka.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-fuel-price-hikes",
    slug: "petrol-diesel-hike-three-rupees-west-asia-costs",
    type: "news-update",
    category: "business",
    tags: ["petrol", "diesel", "OMC losses", "West Asia conflict", "pump prices"],
    kicker: "Business",
    headline: "Petrol and diesel go up by ₹3 a litre, and the losses are only partly covered",
    dek: "The first of several May revisions recovered only part of what the oil companies were losing. By the fourth week of the month the cumulative rise had passed ₹7 a litre and the government had begun asking states to watch the pumps.",
    dateline: "New Delhi",
    publishedAt: "2026-05-18T02:45:00.000Z",
    updatedAt: "2026-05-26T09:05:00.000Z",
    authorId: "a-rohit-banerjee",
    keyPoints: [
      "Petrol and diesel were raised by ₹3 a litre on May 15, described at the time as covering only part of the losses being incurred by the oil marketing companies.",
      "The increase cut their estimated daily losses by about a quarter, to roughly ₹750 crore a day, according to Indian Express reporting on May 18.",
      "The Centre asked states to monitor supplies at retail outlets and check for hoarding and mismanagement.",
    ],
    flags: { trending: true },
    body: [
      {
        kind: "para",
        text: "India raised petrol and diesel prices by ₹3 a litre on May 15, the first of a sequence of revisions that made the second half of May the most expensive fortnight at the pump in recent memory. Prices had been held steady through the first phase of the West Asia disruption, and the increase marked the moment that restraint ended.",
      },
      {
        kind: "para",
        text: "The arithmetic behind the revision is straightforward and unflattering. Indian Express reported on May 15 that the ₹3 covered only part of the losses being borne by the public sector oil marketing companies. Three days later it put the effect more precisely: the increase reduced their estimated daily losses by about a quarter, to roughly ₹750 crore a day.",
      },
      { kind: "subhead", text: "A slow pass-through, made visible" },
      {
        kind: "para",
        text: "What followed was not a single adjustment but a series. On May 19 petrol and diesel were raised by 90 paise a litre, the second increase in under a week. By May 23 the third revision in nine days had added 87 paise to petrol and 91 paise to diesel. Indian Express reported on May 25 that the cumulative rise since May 15 had passed ₹7 a litre, with the companies' losses down to about ₹600 crore a day.",
      },
      {
        kind: "numberline",
        items: [
          "May 15: petrol and diesel up ₹3 a litre.",
          "May 19: up a further 90 paise, the second revision in under a week.",
          "May 23: petrol up 87 paise and diesel up 91 paise, the third revision in nine days.",
          "May 25: cumulative rise of more than ₹7 a litre since May 15; company losses around ₹600 crore a day.",
        ],
      },
      {
        kind: "para",
        text: "Political pressure arrived from both ends. Opposition parties framed the rises as a tax on households already absorbing higher food and transport costs. On the other side, the Punjab government faced demands to cut diesel prices for farmers, a proposal that would have cost it ₹1,650 crore, according to Indian Express reporting on May 27. The Centre also asked states to monitor supplies at retail outlets and check for hoarding and mismanagement.",
      },
      {
        kind: "para",
        text: "For consumers the sequence matters more than any single revision. A ₹3 rise announced on one afternoon reads as a decision. Four increases inside eleven days read as the absence of one, passed on in weekly instalments.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Indian Express coverage of May 15, 18, 19, 23, 25 and 27, 2026 and from Deccan Herald's coverage of the May 15 revision. Pump prices in India vary by state and by retailer; the figures recorded here are the national increases as reported, not any one city's rate.",
      },
    ],
    sources: [
      {
        name: "Indian Express — Explained",
        url: "https://indianexpress.com/article/explained/explained-economics/petrol-diesel-price-hike-india-omc-west-asia-crisis-10690586/",
        date: "2026-05-15",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/petrol-diesel-price-hike-india-rs-3-per-litre-delhi-mumbai-rates-10690278/",
        date: "2026-05-15",
        type: "publication",
      },
      {
        name: "Deccan Herald — India",
        url: "https://www.deccanherald.com/india/prices-of-petrol-and-diesel-raised-by-rs-3-per-litre-amid-west-asia-crisis-check-rates-in-metro-cities-4003658",
        date: "2026-05-15",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/petrol-diesel-price-hike-cuts-omcs-daily-losses-by-a-fourth-current-loss-pegged-at-rs-750-crore-a-day-10695977/",
        date: "2026-05-18",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/petrol-diesel-price-hike-tuesday-omc-losses-west-asia-crisis-10696775/",
        date: "2026-05-19",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/petrol-diesel-price-hike-third-increase-8-days-10703777/",
        date: "2026-05-23",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/petrol-diesel-price-hike-fourth-increase-2-weeks-10706230/",
        date: "2026-05-25",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/petrol-diesel-supply-india-panic-buying-fuel-states-monitoring-10707397/",
        date: "2026-05-25",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a row of fuel dispenser nozzles as flat dark shapes against a stepped bar of four rising blocks in ochre, with a thin rust-coloured chart axis running beneath them.",
      caption: "Four increases in eleven days took the cumulative rise past ₹7 a litre by May 25, 2026.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-namma-metro-solar-blue-line",
    slug: "namma-metro-blue-line-solar-corridor-study",
    type: "news-update",
    category: "technology",
    tags: ["Namma Metro", "Bengaluru", "solar power", "BMRCL", "public transport"],
    kicker: "Bengaluru",
    headline: "The Blue Line could run on sunlight. BMRCL says not without new rules",
    dek: "A study has found that Bengaluru's above-ground metro corridor could support a largely solar-powered operation. Turning that into a power supply runs into land law, storage economics and a regulator that has not been asked the question yet.",
    dateline: "Bengaluru",
    publishedAt: "2026-05-22T04:15:00.000Z",
    authorId: "a-ananya-deshpande",
    keyPoints: [
      "The open stretches of Namma Metro's Blue Line could support a fully solar-powered corridor, Deccan Herald reported on May 19.",
      "BMRCL said on May 22 that running the metro entirely on solar power would require changes to policy and existing infrastructure.",
      "The distinction between generating solar power along the corridor and supplying the whole network is the gap in the proposal.",
    ],
    body: [
      {
        kind: "para",
        text: "There is a long stretch of Namma Metro's Blue Line where the tracks run above ground, and a study has found that this corridor could support a fully solar-powered operation. Deccan Herald reported the finding on May 19, and it is the sort of idea that gets described in a single sentence before anyone has to explain the difficulty.",
      },
      {
        kind: "para",
        text: "The difficulty is the second sentence. BMRCL told Deccan Herald on May 22 that running the metro entirely on solar power would require changes to policy and to existing infrastructure. That is the agency responsible for the network describing its own feasibility work as conditional, which is worth more than the enthusiasm with which the idea was received.",
      },
      { kind: "subhead", text: "Why the open stretches are the whole argument" },
      {
        kind: "para",
        text: "A metro line is a load, not a battery. Trains accelerate, brake and recover energy on a schedule that has nothing to do with the sun, and passengers notice any deviation from that schedule immediately. The attraction of an above-ground corridor is that it offers space for generation close to where the load sits, which is precisely the problem rooftop panels on a station concourse cannot solve.",
      },
      {
        kind: "bullets",
        items: [
          "Generation siting: the open stretches of the Blue Line are where solar can be installed next to the traction load.",
          "Land law: much of that land is public right-of-way, and the permissions for long-term commercial generation there do not yet exist.",
          "Timing: traction demand follows service frequency, not insolation, so a grid-connected hybrid is the realistic first configuration.",
        ],
      },
      {
        kind: "para",
        text: "The useful way to read the study is as a bound rather than a blueprint. It establishes that the physics works along a specific corridor. It does not establish that the institution, the regulations or the land records are ready, and BMRCL's own position is that they are not.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Deccan Herald's coverage of the Blue Line solar corridor study published on May 19, 2026 and from BMRCL's response reported on May 22. NOT SCRIPTED has not seen the study document and does not restate its technical assumptions beyond the cited reporting.",
      },
    ],
    sources: [
      {
        name: "Deccan Herald — Bengaluru",
        url: "https://www.deccanherald.com/india/karnataka/bengaluru/bengaluru-namma-metros-blue-line-could-become-fully-solar-powered-corridor-4008370",
        date: "2026-05-19",
        type: "publication",
      },
      {
        name: "Deccan Herald — Bengaluru",
        url: "https://www.deccanherald.com/india/karnataka/bengaluru/running-metro-entirely-on-solar-power-would-require-policy-and-infra-changes-bmrcl-4013182",
        date: "2026-05-22",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a side-on cross-section of an elevated metro viaduct in silhouette, a thin arc of light passing above it and photovoltaic panels drawn as flat indigo tiles along the deck.",
      caption: "The open stretches of the Blue Line are the only part of the network where solar can be sited next to the traction load.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-bengaluru-civic-polls-deadline",
    slug: "bengaluru-civic-polls-supreme-court-august-deadline",
    type: "news-update",
    category: "karnataka",
    tags: ["BBMP", "ward elections", "Supreme Court", "Bengaluru", "local governance"],
    kicker: "Bengaluru",
    headline: "Bengaluru's ward elections get a date: deadline extended to August 31",
    dek: "Six years without a council has left Bengaluru's wards without elected representation. The court's order sets a finish line for the first time, though the corporation has still to show it can reach one.",
    dateline: "Bengaluru",
    publishedAt: "2026-05-21T03:55:00.000Z",
    updatedAt: "2026-05-24T07:10:00.000Z",
    authorId: "a-priya-shankar",
    keyPoints: [
      "The Supreme Court has extended the final deadline for Bengaluru's civic polls to August 31, 2026.",
      "The city has gone six years without ward elections, which Deccan Herald's May 10 reporting framed as a question of ward-level accountability.",
      "Repeated deferrals have been criticised as procedural abandonment rather than administrative difficulty.",
    ],
    flags: { mostRead: true },
    body: [
      {
        kind: "para",
        text: "The Supreme Court has set August 31, 2026 as the outer deadline for Bengaluru's civic polls, giving the corporation a date it has repeatedly failed to set for itself. Deccan Herald reported the extension of the final deadline on May 21, in a case that has moved between the city corporation, the state government and the court for more than a year.",
      },
      {
        kind: "para",
        text: "The scale of the delay is the story. Bengaluru's wards have gone six years without elected representation. When Deccan Herald examined on May 10 what the elections might change, its focus was not on which party would win but on whether accountability would return to the level of administration residents experience directly, in the form of streetlights, solid waste and potholes.",
      },
      { kind: "subhead", text: "What the deadline does and does not fix" },
      {
        kind: "para",
        text: "A court-set date removes one variable and leaves several. Delimitation of wards, the size of the electorate and the logistics of polling across a metropolitan corporation all still have to be settled, and each can produce a fresh delay if the state's own preparations are incomplete. The extension buys time; it does not guarantee the date.",
      },
      {
        kind: "para",
        text: "It also changes the tone of the debate. Criticism of the repeated deferrals was never really about constitutional nicety. It rested on the observation that a city of Bengaluru's size has been administering wards that no one has elected for six years, which turns a routine local-election cycle into a question about who is making decisions and on whose authority.",
      },
      {
        kind: "callout",
        title: "What residents can actually check",
        text: "If the polls happen, the test is whether ward-level spending decisions and service complaints move at all. Six years of administration by officials rather than representatives is the baseline any new council will be measured against, and no court order changes that baseline.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Deccan Herald's coverage of the Supreme Court's deadline order published on May 21, 2026 and its earlier coverage of the civic poll question published on May 10. NOT SCRIPTED has not obtained the order itself and has not spoken to the corporation or to any political party.",
      },
    ],
    sources: [
      {
        name: "Deccan Herald — Karnataka",
        url: "https://www.deccanherald.com/india/karnataka/b-luru-civic-polls-sc-extends-final-deadline-till-aug-31-4010511",
        date: "2026-05-21",
        type: "publication",
      },
      {
        name: "Deccan Herald — Bengaluru",
        url: "https://www.deccanherald.com/india/karnataka/bengaluru/bengaluru-civic-polls-after-six-yearshopes-of-ward-level-accountability-revived-3998112",
        date: "2026-05-10",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a stylised city ward map as irregular polygons in warm cream, one polygon stamped in solid rust, with a long shadow cast away from it across the grid.",
      caption: "Bengaluru's wards have gone six years without an elected representative; the court has now set August 31 as the limit.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-karuppu-box-office",
    slug: "karuppu-box-office-tamil-nine-month-drought",
    type: "news-update",
    category: "culture",
    tags: ["Tamil cinema", "Karuppu", "Suriya", "box office", "Jyotika"],
    kicker: "Culture",
    headline: "Karuppu ends the Tamil film industry's nine-month drought",
    dek: "Suriya's film crossed ₹200 crore globally within a week of release and became the year's biggest Tamil hit. The makers have also apologised for an uncomfortable shot aimed at a composer.",
    dateline: "Chennai",
    publishedAt: "2026-05-24T05:00:00.000Z",
    updatedAt: "2026-05-28T10:20:00.000Z",
    authorId: "a-revathi-kumar",
    keyPoints: [
      "Karuppu took in ₹175 crore globally by its sixth day, according to Indian Express reporting on May 21.",
      "By May 23 it had crossed ₹200 crore and ended a nine-month drought in the Tamil box office.",
      "The makers apologised on May 19 for a shot that appeared to target the composer Ilaiyaraaja, saying the scene would be modified or removed.",
    ],
    body: [
      {
        kind: "para",
        text: "Karuppu, starring Suriya with Jyotika in the lead, took in ₹175 crore globally by its sixth day, Indian Express reported on May 21. Two days later the same outlet recorded the film crossing ₹200 crore and ending a nine-month drought in the Tamil box office. By May 24 it had passed ₹217 crore worldwide and the lead actor was publicly hinting at a sequel.",
      },
      {
        kind: "para",
        text: "The commercial shape of that run is unusual enough to be worth pausing on. A film that reaches ₹200 crore inside a week, in a market that had gone nine months without a comparable result, is not simply a hit. It is the event that resets a quarter, and it does so while the political conversation in the same state is being reorganised around a film star's next move.",
      },
      { kind: "subhead", text: "The apology" },
      {
        kind: "para",
        text: "Not everything went smoothly. On May 19 the makers apologised for a shot in the film that appeared to target the composer Ilaiyaraaja, and said the scene would be modified or removed. In a regional industry where a single jab can be picked up and amplified across every district, a voluntary correction is a small event with a large shadow.",
      },
      {
        kind: "para",
        text: "Jyotika, who produced and starred in the film, described the last ten minutes as the part Suriya carried, and later said she missed being in her own language after returning to Mumbai. Both remarks belong to a release that functioned as a statement of regional identity while also being, plainly, a commercial success.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Indian Express's Tamil film coverage of May 19, 21, 23 and 24, 2026. Box office figures for Indian films are estimates reported by trade outlets and are not audited; they are recorded here as reported.",
      },
    ],
    sources: [
      {
        name: "Indian Express — Entertainment",
        url: "https://indianexpress.com/article/entertainment/tamil/karuppu-box-office-collection-day-6-suriya-rs-175-cr-10700790/",
        date: "2026-05-21",
        type: "publication",
      },
      {
        name: "Indian Express — Entertainment",
        url: "https://indianexpress.com/article/entertainment/tamil/suriyas-karuppu-crosses-rs-200-cr-globally-biggest-hit-tamil-nadu-box-office-10704094/",
        date: "2026-05-23",
        type: "publication",
      },
      {
        name: "Indian Express — Entertainment",
        url: "https://indianexpress.com/article/entertainment/tamil/suriyas-karuppu-crosses-rs-217-crore-worldwide-actor-hints-at-sequel-10705289/",
        date: "2026-05-24",
        type: "publication",
      },
      {
        name: "Indian Express — Entertainment",
        url: "https://indianexpress.com/article/entertainment/tamil/suriyas-karuppu-makers-apologise-for-ilaiyaraaja-jab-in-the-film-statement-10698143/",
        date: "2026-05-19",
        type: "publication",
      },
      {
        name: "Indian Express — Entertainment",
        url: "https://indianexpress.com/article/entertainment/tamil/jyotika-on-the-success-of-karuppu-suriya-performed-brilliantly-in-the-last-ten-minutes-10701717/",
        date: "2026-05-21",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a wide cinema screen rendered as a soft rectangle of light with small ticket-stub rectangles scattering away from it across a deep plum background.",
      caption: "Karuppu crossed ₹200 crore globally within a week and ended a nine-month Tamil box-office drought.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-us-iran-deal-hormuz",
    slug: "us-iran-deal-hormuz-reopening-details",
    type: "news-update",
    category: "geopolitics",
    tags: ["Strait of Hormuz", "US Iran talks", "ceasefire", "enrichment", "oil markets"],
    kicker: "Geopolitics",
    headline: "The US-Iran talks: what reopening Hormuz actually involves",
    dek: "Details reported on May 24 tied three questions together — a shipping strait, an enrichment ceiling and a verification mechanism. Two days later, US forces struck Iranian missile sites anyway.",
    dateline: "Dubai",
    publishedAt: "2026-05-26T03:05:00.000Z",
    updatedAt: "2026-05-29T06:00:00.000Z",
    authorId: "a-leila-haddad",
    keyPoints: [
      "Details reported on May 24 covered a US-Iran understanding involving reopening of the Strait of Hormuz and limits on enriched uranium, in reporting that also placed US Secretary of State Marco Rubio in the negotiations.",
      "On May 26 the US conducted what it described as self-defence strikes against Iranian missile sites despite ceasefire talks.",
      "For importers in the Gulf, a reopened strait and a struck launch site are two entirely different problems.",
    ],
    body: [
      {
        kind: "para",
        text: "Details of a US-Iran understanding began to be reported on May 24, and they were more specific than the previous round of ceasefire announcements. Indian Express described them as covering three linked subjects: reopening of the Strait of Hormuz, limits on enriched uranium, and verification, in reporting that also placed the US Secretary of State, Marco Rubio, in the negotiations.",
      },
      {
        kind: "para",
        text: "The strategic weight of that list is out of proportion to its length. The Strait of Hormuz carries a large share of seaborne crude, and the fuel prices at Indian pumps through May 2026 were, in the most direct way imaginable, a Hormuz price. Enrichment limits are the other half of the same bargain, because an arrangement that reopened the waterway without constraining the programme would be a pause rather than a settlement.",
      },
      { kind: "subhead", text: "Then the strikes" },
      {
        kind: "para",
        text: "On May 26 the US conducted what it described as self-defence strikes against Iranian missile sites even as ceasefire talks continued, Indian Express reported the same day. The sequence is the point: an understanding detailed enough to publish on a Tuesday did not survive the following Monday.",
      },
      {
        kind: "para",
        text: "For energy markets the distinction between a reopened strait and a struck launch site is not rhetorical. One is a logistics problem with a known solution. The other is a risk premium, and risk premiums are re-priced by headlines rather than by diplomatic language.",
      },
      {
        kind: "callout",
        title: "Why this belongs in an Indian newspaper",
        text: "Indian retail fuel prices, the rupee, the fertiliser import bill and the freight cost of Indian exports all sit downstream of this one waterway. The Strait of Hormuz is a Gulf story in origin and an Indian macroeconomic story in consequence.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Indian Express's world desk coverage published on May 24, 26 and 29, 2026 and its May 30 explained piece on Asian oil importers. NOT SCRIPTED has not seen the text of any agreement and does not characterise terms beyond what the cited reporting records.",
      },
    ],
    sources: [
      {
        name: "Indian Express — World",
        url: "https://indianexpress.com/article/world/donald-trump-iran-deal-strait-of-hormuz-reopening-nuclear-uranium-marco-rubio-10705726/",
        date: "2026-05-24",
        type: "publication",
      },
      {
        name: "Indian Express — World",
        url: "https://indianexpress.com/article/world/us-conducts-self-defence-strikes-iran-missile-sites-ceasefire-talks-10707846/",
        date: "2026-05-26",
        type: "publication",
      },
      {
        name: "Indian Express — World",
        url: "https://indianexpress.com/article/world/iran-strait-of-hormuz-ceasefire-proposal-us-talks-10714734/",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Indian Express — Explained",
        url: "https://indianexpress.com/article/explained/explained-economics/china-oil-imports-india-strait-of-hormuz-crisis-explained-10715192/",
        date: "2026-05-30",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a narrow horizontal channel of dark water cutting between two flat land masses, small angular vessel shapes caught in the current and a segmented arc spanning the gap above.",
      caption: "An understanding on Hormuz reopening published on May 24 did not survive the US strikes of May 26.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-karnataka-chief-minister-change",
    slug: "siddaramaiah-resigns-shivakumar-karnataka-chief-minister",
    type: "news-update",
    category: "karnataka",
    tags: ["Karnataka", "chief minister", "D K Shivakumar", "Siddaramaiah", "Congress"],
    kicker: "Bengaluru & Karnataka",
    headline: "Siddaramaiah resigns; D K Shivakumar emerges as front-runner",
    dek: "The Karnataka chief minister left for Delhi on May 28 after submitting his resignation, and a senior party leader moved into clear contention for the post. The state faces a change of government weeks after its assembly election.",
    dateline: "Bengaluru",
    publishedAt: "2026-05-28T02:30:00.000Z",
    authorId: "a-vikram-nadkarni",
    keyPoints: [
      "D K Shivakumar emerged as the front-runner to replace Siddaramaiah as Karnataka's chief minister, Deccan Herald reported on May 27.",
      "Siddaramaiah departed for Delhi on May 28 after resigning, Deccan Herald reported the same day.",
      "The succession comes in the immediate aftermath of Karnataka's assembly election, which reshaped the state's political arithmetic.",
    ],
    flags: { breaking: true },
    body: [
      {
        kind: "para",
        text: "Siddaramaiah has resigned as chief minister of Karnataka and left for Delhi, Deccan Herald reported on May 28. The departure came a day after the ruling party had begun settling its own process for choosing a successor, and it confirms a change of government in a state whose assembly arithmetic had already been rewritten by an election weeks earlier.",
      },
      {
        kind: "para",
        text: "D K Shivakumar, a senior party leader, had emerged as the front-runner to replace him, Deccan Herald reported on May 27. Both reports describe the same mechanism: a formal process, an identified favourite, and a decision the party leadership was expected to ratify.",
      },
      { kind: "subhead", text: "A change of government by another route" },
      {
        kind: "para",
        text: "The unusual feature of this transition is that it arrives through internal party management rather than an electoral defeat in mid-term. That normally buys a government room, since the coalition it was elected on has not yet faced a fresh confidence test. It also means the state's priorities are about to be set by someone who did not build the outgoing team's programme.",
      },
      {
        kind: "para",
        text: "For Bengaluru the immediate questions are administrative rather than ideological. The state capital is midway through several long-running infrastructure programmes, and a change of chief minister resets the priority sequence even when the stated policy direction does not change.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Deccan Herald's Karnataka coverage published on May 27 and 28, 2026. NOT SCRIPTED has not confirmed the date of the oath ceremony, which subsequent Deccan Herald reporting placed outside this reporting window.",
      },
    ],
    sources: [
      {
        name: "Deccan Herald — Karnataka",
        url: "https://www.deccanherald.com/india/karnataka/d-k-shivakumar-emerges-as-front-runner-to-replace-siddaramaiah-as-karnataka-chief-minister-4017549",
        date: "2026-05-27",
        type: "publication",
      },
      {
        name: "Deccan Herald — Karnataka",
        url: "https://www.deccanherald.com/india/karnataka/cm-siddaramaiah-to-be-replaced-as-karnataka-chief-minister-4018395",
        date: "2026-05-27",
        type: "publication",
      },
      {
        name: "Deccan Herald — Karnataka",
        url: "https://www.deccanherald.com/india/karnataka/siddaramaiah-departs-for-delhi-after-resigning-as-karnataka-chief-minister-4019451",
        date: "2026-05-28",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: two empty chair-like geometric frames side by side, one in warm rust and slightly rotated, the other flat cream, on a plain ochre ground with a long diagonal shadow.",
      caption: "Karnataka's chief ministerial change of May 2026 was settled inside the party rather than by a fresh election.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-supreme-court-sir-verdict",
    slug: "supreme-court-upholds-sir-orders-ec-to-report-deletions",
    type: "news-update",
    category: "india",
    tags: ["Supreme Court", "Election Commission", "SIR", "electoral rolls", "citizenship"],
    kicker: "India",
    headline: "Supreme Court upholds the SIR, then tells the EC to report every deletion",
    dek: "The court has accepted the commission's revised electoral-roll methodology and set a citizenship question running alongside it. The order gives the exercise a legal foundation and a new obligation at the same time.",
    dateline: "New Delhi",
    publishedAt: "2026-05-31T03:30:00.000Z",
    authorId: "a-nandini-rao",
    keyPoints: [
      "The Supreme Court has upheld the Election Commission's special intensive revision of electoral rolls and directed the commission to report the names it has deleted, Indian Express reported on May 28.",
      "The order sets the stage for a citizenship test to be applied to those flagged during the revision.",
      "Chief Election Commissioner Gyanesh Kumar responded on May 30 by arguing that fair rolls are a precondition for fair polls.",
    ],
    flags: { topStory: true },
    body: [
      {
        kind: "para",
        text: "The Supreme Court has upheld the Election Commission's special intensive revision of electoral rolls and directed the commission to report the names it has deleted. Indian Express reported the ruling on May 28, describing the direction as the first half of a judgment whose second half opens a citizenship question attached to the revision.",
      },
      {
        kind: "para",
        text: "That pairing is what makes the judgment significant rather than merely procedural. A roll-revision exercise and a test of citizenship are different instruments with different legal standards, and a court that validates the first while forwarding the second has not narrowed the exercise so much as given it a named risk.",
      },
      { kind: "subhead", text: "What the court has and has not settled" },
      {
        kind: "para",
        text: "The verdict resolved the challenge to the methodology. It did not settle what happens to a person whose name has been removed, and the reporting on the order was consistent on this point: the commission has been told to report deletions rather than left to apply consequences on its own. For an Election Commission operating by notification, that is a meaningful limit.",
      },
      {
        kind: "para",
        text: "The political response was immediate and polarised. Indian Express's own editorial on May 29 argued that the commission had much to answer for even after being given a clean chit by the court, and other reporting recorded opposition parties saying the judgment raises more questions than it answers. Chief Election Commissioner Gyanesh Kumar's response on May 30 was the institutional one: fair rolls are a precondition for fair polls, and the argument about the method is separate from the argument about the timing.",
      },
      {
        kind: "callout",
        title: "Why the deletion list matters",
        text: "A roll revision judged in principle still has to be executed name by name. The court's direction to report deletions is the mechanism by which a person who believes they were wrongly removed can find out that they were, and it is the point at which the judgment becomes operational rather than rhetorical.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Indian Express's coverage of the Supreme Court judgment of May 28, its editorial of May 29 and its reporting on the Election Commissioner's response of May 30, 2026. NOT SCRIPTED has not read the judgment itself and does not paraphrase its reasoning beyond the cited coverage.",
      },
    ],
    sources: [
      {
        name: "Indian Express — Explained",
        url: "https://indianexpress.com/article/explained/explained-law/sir-ruling-supreme-court-election-commission-report-deleted-names-citizenship-10711472/",
        date: "2026-05-28",
        type: "publication",
      },
      {
        name: "Indian Express — Legal News",
        url: "https://indianexpress.com/article/legal-news/supreme-court-verdict-on-sir-raises-more-questions-than-it-answers-opposition-10711489/",
        date: "2026-05-28",
        type: "publication",
      },
      {
        name: "Indian Express — Opinion",
        url: "https://indianexpress.com/article/opinion/editorials/ec-has-a-lot-to-answer-but-sc-gives-it-a-free-pass-and-more-10713045/",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Indian Express — India",
        url: "https://indianexpress.com/article/india/cec-gyanesh-kumar-electoral-rolls-special-intensive-revision-supreme-court-fair-polls-10716082/",
        date: "2026-05-30",
        type: "publication",
      },
      {
        name: "Indian Express — Explained",
        url: "https://indianexpress.com/article/explained/explained-law/supreme-court-eci-special-intensive-revision-sir-citizenship-10716723/",
        date: "2026-05-31",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a tall stack of identical paper sheets with a single sheet drawn slightly askew, one row of names rendered as small dark ticks and a few ticks boxed in red.",
      caption: "A roll-revision exercise validated in principle still has to be executed name by name.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-three-f-squeeze",
    slug: "three-f-squeeze-fuel-fertiliser-foreign-exchange-may-2026",
    type: "original",
    category: "business",
    tags: ["fuel prices", "fertiliser imports", "forex reserves", "rupee", "West Asia"],
    kicker: "Original",
    headline: "The 3F squeeze: fuel, fertiliser and the foreign exchange to buy both",
    dek: "The finance minister named the problem in May: fuel, fertiliser and foreign exchange, all three moving against India at once. Working from the published price and trade figures, the third constraint is the one that turns two problems into one.",
    dateline: "New Delhi",
    publishedAt: "2026-05-30T02:05:00.000Z",
    updatedAt: "2026-06-01T06:45:00.000Z",
    authorId: "a-karan-malhotra",
    keyPoints: [
      "Finance minister Nirmala Sitharaman framed the West Asia shock as a '3F' problem — fuel, fertiliser and foreign exchange — in a speech in Mumbai on May 25.",
      "The cumulative fuel price increase from May 15 passed ₹7 a litre by May 25, according to Indian Express reporting.",
      "Gross foreign direct investment into India hit a record $95 billion in FY2026 while net inflows were $7.7 billion, Indian Express reported on May 22.",
    ],
    body: [
      {
        kind: "para",
        text: "The most useful thing anyone said about India's macroeconomic position in May 2026 was a three-letter abbreviation. Finance minister Nirmala Sitharaman flagged what she called the '3F' challenge — fuel, fertiliser and foreign exchange — in a speech in Mumbai on May 25, and Indian Express reported the same day that the reference also covered gold and the rupee.",
      },
      {
        kind: "para",
        text: "The framing is useful precisely because it refuses to treat the three as separate. They are the same bill arriving in different currencies. Crude and fertiliser are both imported, both are denominated in dollars, and a currency that weakens against the dollar makes both more expensive at the same time, before either price has moved.",
      },
      { kind: "subhead", text: "Working the numbers rather than the narrative" },
      {
        kind: "para",
        text: "The fuel leg is the one with public numbers attached. Indian Express reported on May 25 that the cumulative increase since May 15 had passed ₹7 a litre, with the oil marketing companies' losses down to about ₹600 crore a day. The sequence matters: four increases inside eleven days is a pass-through decision made in steps rather than one.",
      },
      {
        kind: "bullets",
        items: [
          "Fuel: petrol and diesel up ₹3 a litre on May 15, then three further revisions by May 23, taking the cumulative rise past ₹7 a litre.",
          "Fertiliser: Indian Express reported on May 25 that India's fertiliser import bill is rising as the rupee weakens and Gulf supply routes are disrupted.",
          "Foreign exchange: gross FDI into India reached a record $95 billion in FY2026, but net inflows were $7.7 billion.",
        ],
      },
      {
        kind: "para",
        text: "The FDI line is the one that gets skipped, and it should not. A record gross figure and a net figure an order of magnitude smaller are not in contradiction; they describe different things. The first is capital committed. The second is what actually stayed in the economy after repatriation and offsetting outflows. For a country whose external account matters most in a bad month, the second number is the relevant one.",
      },
      {
        kind: "para",
        text: "The government's own review was cautious. The finance ministry's May economic review, reported on May 30, said the inflation outlook warrants vigilance and that consumption may face headwinds. That is a document conceding that the pass-through is not finished, which is consistent with everything else in the month's record.",
      },
      {
        kind: "callout",
        title: "Why the third F governs the other two",
        text: "Fuel and fertiliser bills are denominated in dollars. A weaker rupee raises both without a single barrel of crude or tonne of fertiliser changing hands. The exchange rate is therefore not a fourth problem in this list. It is the multiplier on the first two.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: NOT SCRIPTED compiled this article independently from the dated figures reported by Indian Express and Deccan Herald in May 2026 and from the petroleum statistics published by the Petroleum Planning and Analysis Cell. None of the cited publications reproduces the aggregation of the three constraints set out here. No interviews were conducted and no proprietary dataset was used.",
      },
    ],
    sources: [
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/fm-nirmala-sitharaman-sidbi-mumbai-speech-forex-crude-gold-rupee-crisis-10707157/",
        date: "2026-05-25",
        type: "publication",
      },
      {
        name: "Indian Express — India",
        url: "https://indianexpress.com/article/india/nirmala-sitharaman-west-asia-crisis-petrol-diesel-fuel-prices-msme-impact-10707049/",
        date: "2026-05-25",
        type: "publication",
      },
      {
        name: "Indian Express — Explained",
        url: "https://indianexpress.com/article/explained/explained-economics/iran-weaker-rupee-impact-india-fertiliser-import-bill-10705935/",
        date: "2026-05-25",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/economy/gross-fdi-into-india-hit-new-record-of-95-billion-in-fy26-but-net-inflows-only-7-7-billion-10703213/",
        date: "2026-05-22",
        type: "publication",
      },
      {
        name: "Indian Express — UPSC Essentials",
        url: "https://indianexpress.com/article/upsc-current-affairs/upsc-essentials/upsc-issue-indias-challenge-fuel-fertiliser-foreign-exchange-west-asia-war-10710360/",
        date: "2026-05-28",
        type: "publication",
      },
      {
        name: "Indian Express — Business",
        url: "https://indianexpress.com/article/business/finance-ministry-may-economic-review-inflation-west-asia-conflict-monsoon-10715482/",
        date: "2026-05-30",
        type: "publication",
      },
      {
        name: "Petroleum Planning and Analysis Cell, Ministry of Petroleum and Natural Gas",
        url: "https://ppac.gov.in/",
        type: "data",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: three interlocking rings drawn as flat geometric bands in rust, ochre and deep teal, overlapping across a faint gridded chart with a downward line running beneath them.",
      caption: "Fuel, fertiliser and foreign exchange are one problem expressed in three currencies.",
      credit: "Illustration: NOT SCRIPTED",
    },
    sourcingNote:
      "NOT SCRIPTED independently compiled this from the dated fuel price revisions reported by Indian Express and Deccan Herald in May 2026, the finance ministry's May economic review as reported on May 30, the published FY2026 FDI aggregates reported on May 22, and the petroleum statistics published by the Petroleum Planning and Analysis Cell. None of these reproduces the aggregation of the three constraints set out here. No interviews were conducted.",
  },
  {
    id: "ns-2026-05-monsoon-downgrade",
    slug: "imd-cuts-southwest-monsoon-forecast-to-ninety-percent",
    type: "explainer",
    category: "environment",
    tags: ["IMD", "monsoon", "rainfall", "Kerala", "agriculture"],
    kicker: "Explainer",
    headline: "The monsoon forecast fell to 90%. Here is what that number actually controls",
    dek: "The IMD has downgraded its seasonal outlook for the southwest monsoon to 90% of the long-period average, with below-normal rainfall forecast for three of the four regions. The percentage is a national average, and that is where its weakness lies.",
    dateline: "New Delhi",
    publishedAt: "2026-05-29T01:40:00.000Z",
    updatedAt: "2026-06-02T04:30:00.000Z",
    authorId: "a-tara-iyengar",
    keyPoints: [
      "The IMD downgraded its southwest monsoon seasonal outlook to 90% of the long-period average, forecasting below-normal rainfall in three of the four regions, Deccan Herald reported on May 29.",
      "Indian Express reported the same day that the revision pointed to the driest monsoon in a decade.",
      "The June 1 Kerala onset was expected to be missed, Indian Express reported on May 30, and Mumbai recorded its driest May in three years.",
    ],
    flags: { editorsPick: true },
    body: [
      {
        kind: "para",
        text: "The India Meteorological Department has downgraded its seasonal outlook for the southwest monsoon to 90% of the long-period average, with below-normal rainfall forecast for three of the four rainfall regions. Deccan Herald reported the revision on May 29. Indian Express described the same downgrade as pointing towards the driest monsoon in a decade.",
      },
      {
        kind: "para",
        text: "A national percentage is the wrong unit of anxiety, and understanding why is most of what there is to understand about a seasonal forecast. The long-period average is calculated across the whole country. A monsoon that delivers 90% of it can be catastrophic for the districts that receive the deficit and unremarkable for the districts that do not.",
      },
      { kind: "subhead", text: "Why 90% is not a mild forecast" },
      {
        kind: "para",
        text: "The agricultural economy is not exposed to the national average. It is exposed to the timing of the onset, the distribution of rain across the first weeks, and whether a dry spell lands on a critical crop stage. A below-normal seasonal total with a normal onset can be managed; a normal total with a late onset and a bad June cannot. Indian Express reported on May 30 that the June 1 Kerala onset was expected to be missed, and on May 31 that Mumbai had recorded its driest May in three years.",
      },
      {
        kind: "numberline",
        items: [
          "Seasonal outlook: 90% of the long-period average for the southwest monsoon.",
          "Regions: below-normal rainfall forecast in three of four.",
          "Onset: the June 1 Kerala arrival was expected to be missed.",
          "Ground truth: Mumbai's driest May in three years.",
        ],
      },
      {
        kind: "para",
        text: "The IMD's monthly and weekly updates will supersede the seasonal figure many times over, and seasonal forecasts carry genuine error. But the revision is not a technicality. It moves reservoir planning, crop choice, kharif sowing decisions and state relief expectations, all of which are committed well before anyone knows whether the number held.",
      },
      {
        kind: "callout",
        title: "How to hold a seasonal forecast",
        text: "Treat the percentage as a planning input rather than a prediction, and watch the regional distribution rather than the national total. An early seasonal deficit concentrated in one or two regions is a different event from a uniform ten per cent shortfall, and the two require different responses.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this explainer was written retrospectively by NOT SCRIPTED from Deccan Herald's report of the IMD's revised seasonal outlook published on May 29, 2026 and from Indian Express coverage of the same revision, the Kerala onset and Mumbai's rainfall record published on May 29, 30 and 31. Subsequent official monsoon updates fall outside this reporting window and are not reflected here.",
      },
    ],
    sources: [
      {
        name: "Deccan Herald — India",
        url: "https://www.deccanherald.com/india/imd-downgrades-south-west-monsoon-outlook-to-90-predicts-below-normal-rainfall-in-3-out-of-4-regions-4020613",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Indian Express — India",
        url: "https://indianexpress.com/article/india/southwest-monsoon-kerala-onset-delay-imd-forecast-rainfall-10715946/",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Indian Express — India",
        url: "https://indianexpress.com/article/india/monsoon-advances-imd-warns-heatwave-heavy-rain-thunderstorm-across-india-10713383/",
        date: "2026-05-30",
        type: "publication",
      },
      {
        name: "Indian Express — Mumbai",
        url: "https://indianexpress.com/article/cities/mumbai/mumbai-sees-driest-may-in-3-years-pre-monsoon-showers-imd-deficit-rain-update-10717012/",
        date: "2026-05-31",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a broad field of thin vertical strokes of uneven height in shades of green and dry ochre, with a single flat line drawn across them marking a level just below the average of the field.",
      caption: "A national monsoon figure of 90% can hide a severe deficit in the districts that farm it.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-neet-ug-from-the-web",
    slug: "neet-ug-2026-cancelled-what-the-reporting-shows",
    type: "from-the-web",
    category: "india",
    tags: ["NEET UG", "NTA", "paper leak", "CBI", "Supreme Court"],
    kicker: "From Around The Web",
    headline: "NEET-UG 2026 was cancelled. Here is what three weeks of reporting established",
    dek: "The exam was scrapped after allegations of a paper leak, the agency was examined in court, and thirteen people were arrested. A summary of what the published reporting actually established, and what it did not.",
    dateline: "New Delhi",
    publishedAt: "2026-05-29T06:50:00.000Z",
    authorId: "a-not-scripted-desk",
    keyPoints: [
      "The National Testing Agency told the Supreme Court it had taken all precautions and scrapped NEET-UG 2026 after inputs of malpractice, Indian Express reported on May 29.",
      "The CBI's investigation had reached thirteen arrests by May 28, including a Latur-based doctor and a Pune teacher.",
      "The Supreme Court described the episode as traumatic for students and parents and set the next hearing for July; the NTA extended the fee-refund deadline to June 22.",
    ],
    flags: { trending: true },
    body: [
      {
        kind: "para",
        text: "This is a summary of reporting published by other outlets, written by NOT SCRIPTED. The underlying facts come from Indian Express's education, legal and national coverage between May 12 and May 31, 2026, and from what the National Testing Agency told the Supreme Court in a filed affidavit. Readers who want the full accounts should go to those reports.",
      },
      {
        kind: "para",
        text: "The sequence that the reporting established is clear. NEET-UG 2026 was cancelled after allegations that the question paper had leaked. The agency told the court on May 29 that it had taken all the precautions it could and had scrapped the exam after receiving inputs of malpractice. The cancellation was therefore an agency decision under pressure, not a court order, which is a distinction that matters for who bears responsibility.",
      },
      { kind: "subhead", text: "What the investigation had reached" },
      {
        kind: "para",
        text: "By May 28 the Central Bureau of Investigation had arrested thirteen people, among them a Latur-based doctor and a Pune teacher. Indian Express also reported that some candidates had been required to surrender original documents and return later to pay fees, and that the government was examining using the Air Force to transport question papers for a retest. The Supreme Court called the episode very traumatic for students and parents and set the next hearing for July.",
      },
      {
        kind: "bullets",
        items: [
          "Cancellation: the NTA scrapped NEET-UG 2026 after inputs of malpractice, according to its affidavit to the Supreme Court.",
          "Arrests: thirteen people in the CBI net by May 28, including a Latur-based doctor and a Pune teacher.",
          "Remedies: the NTA extended the fee-refund deadline to June 22 and told the court it would use AI tools for 85% of exam translation.",
          "Court: the Supreme Court set the next hearing for July 2026.",
        ],
      },
      {
        kind: "para",
        text: "Two further items belong in the same file because they concern the same institution in the same period. Indian Express reported on May 30 that CUET-UG 2026 was disrupted nationwide by a technical glitch that delayed exams for thousands, and on May 28 that CBSE had answered allegations about an on-screen marking contractor while calling the claims misleading. Neither is the NEET story. Both are the same institution's month.",
      },
      {
        kind: "callout",
        title: "What the reporting did not establish",
        text: "The published record identifies arrests and allegations. It does not establish how the paper was obtained, who paid for it, or whether the mechanism was a single breach or a network. Those questions were open when the Supreme Court adjourned in May, and this summary does not close them.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this article summarises reporting published by Indian Express between May 12 and May 31, 2026, including its May 31 explainer on how the safeguards around NEET-UG were designed to fail, and the NTA's account of the cancellation given in its Supreme Court affidavit. NOT SCRIPTED wrote this summary and did not conduct any of the reporting it describes.",
      },
    ],
    sources: [
      {
        name: "Indian Express — Education",
        url: "https://indianexpress.com/article/education/neet-was-supposed-to-be-leak-proof-in-2026-heres-how-the-system-built-to-protect-the-exam-failed-10716204/",
        date: "2026-05-31",
        type: "publication",
      },
      {
        name: "Indian Express — Legal News",
        url: "https://indianexpress.com/article/legal-news/nta-supreme-court-affidavit-neet-ug-2026-cancellation-reasons-cbi-probe-ai-biometrics-10713942/",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Indian Express — Legal News",
        url: "https://indianexpress.com/article/legal-news/nta-supreme-court-affidavit-neet-ug-paper-leak-ai-translation-cbt-mode-10714354/",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Indian Express — Education",
        url: "https://indianexpress.com/article/education/neet-ug-2026-paper-leak-supreme-court-hearing-faima-udf-10712278/",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Indian Express — India",
        url: "https://indianexpress.com/article/india/neet-paper-leak-probe-latur-based-doctor-pune-teacher-in-cbi-net-13-arrests-so-far-10711480/",
        date: "2026-05-28",
        type: "publication",
      },
      {
        name: "Indian Express — India",
        url: "https://indianexpress.com/article/india/govt-air-force-logistics-support-neet-retest-10712789/",
        date: "2026-05-28",
        type: "publication",
      },
      {
        name: "Indian Express — Education",
        url: "https://indianexpress.com/article/education/neet-ug-2026-nta-extends-deadline-for-fee-refund-submission-neet-nta-nic-in-10711649/",
        date: "2026-05-28",
        type: "publication",
      },
      {
        name: "Indian Express — Education",
        url: "https://indianexpress.com/article/education/nta-cuet-ug-disrupted-exam-delayed-technical-glitch-tsc-exam-centre-nationwide-delhi-noida-varanasi-cuet-nta-nic-in-10715583/",
        date: "2026-05-30",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a stack of sealed examination envelopes rendered as flat rectangles, one of them opened and emptied, with a faint repeating grid of identical small squares receding behind it.",
      caption: "The NTA told the Supreme Court it scrapped NEET-UG 2026 after receiving inputs of malpractice.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-israel-beaufort-castle",
    slug: "israel-seizes-beaufort-castle-deepest-lebanon-incursion",
    type: "news-update",
    category: "world",
    tags: ["Israel", "Lebanon", "Beaufort Castle", "ground incursion", "ceasefire"],
    kicker: "World",
    headline: "Israel seizes Beaufort Castle in its deepest Lebanon incursion in 26 years",
    dek: "The capture of a fortress overlooking the Mediterranean approaches marks a physical change on the ground, not a change of statement, in a conflict whose diplomacy has repeatedly outrun its front line.",
    dateline: "Beirut",
    publishedAt: "2026-05-31T01:15:00.000Z",
    authorId: "a-helena-costa",
    keyPoints: [
      "Israeli forces captured Beaufort Castle in what Indian Express reported on May 31 as the deepest Israeli incursion into Lebanon in 26 years.",
      "The site overlooks the Mediterranean approaches and the coastal road linking Beirut and Sidon.",
      "A change on the ground of this kind is materially different from another round of statements about readiness to act.",
    ],
    flags: { breaking: true },
    body: [
      {
        kind: "para",
        text: "Israeli forces have captured Beaufort Castle in southern Lebanon, in what Indian Express reported on May 31 as the deepest Israeli incursion into the country in 26 years. The fortress sits on a promontory above the sea, commanding the coastal route between Beirut and Sidon.",
      },
      {
        kind: "para",
        text: "The significance is as much positional as symbolic. A crossing on the ground does something that a statement does not: it changes what any subsequent negotiation has to account for. Terms written before the capture are now terms written against a different map.",
      },
      { kind: "subhead", text: "Why 26 years is the useful comparison" },
      {
        kind: "para",
        text: "The quarter-century framing is doing real work in the coverage. It places the move against the last time Israeli forces occupied ground in this part of Lebanon, and it signals to all parties that the stated red lines of a ceasefire are being tested by presence rather than rhetoric.",
      },
      {
        kind: "para",
        text: "For the region's diplomacy, the practical consequence is the usual one. Such moves tend to be followed either by a withdrawal negotiated quietly or by a deepening of the deployment. What neither course avoids is a period in which the border is not where anyone planned to leave it.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Indian Express's world desk coverage published on May 31, 2026. NOT SCRIPTED has no correspondent at the site and has not verified the position of the forces independently beyond the cited reporting.",
      },
    ],
    sources: [
      {
        name: "Indian Express — World",
        url: "https://indianexpress.com/article/world/israeli-forces-capture-lebanon-beaufort-castle-ground-invasion-10716772/",
        date: "2026-05-31",
        type: "publication",
      },
      {
        name: "Indian Express — World",
        url: "https://indianexpress.com/article/world/israel-troops-lebanon-military-talks-pentagon-10714957/",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a heavy stone fort rendered as a stack of flat blocky shapes on a narrow headland, with a dark sea plane behind it and a single pale line marking the coastline.",
      caption: "The capture of Beaufort Castle changes the map that any ceasefire negotiation would have to work from.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
  {
    id: "ns-2026-05-ipl-final-rcb",
    slug: "ipl-2026-final-rcb-beat-gujarat-titans",
    type: "news-update",
    category: "sports",
    tags: ["IPL", "cricket", "Royal Challengers Bengaluru", "Gujarat Titans", "final"],
    kicker: "Sports",
    headline: "The IPL final ended the way Bengaluru's season finally allowed it to",
    dek: "Royal Challengers Bengaluru beat Gujarat Titans in the final after a league and knockouts in which the same two teams met repeatedly. Kohli's fastest half-century in an IPL final was the record; the season was the story.",
    dateline: "Bengaluru",
    publishedAt: "2026-05-31T14:20:00.000Z",
    authorId: "a-vinay-karnik",
    keyPoints: [
      "Royal Challengers Bengaluru won the IPL 2026 final against Gujarat Titans, Indian Express reported on May 31.",
      "Virat Kohli's innings included the fastest fifty in an IPL final, a record Indian Express reported the same day.",
      "Gujarat Titans had reached the final by Gill's 104 in the qualifier, at the expense of Vaibhav Sooryavanshi's 96.",
    ],
    flags: { mostRead: true },
    body: [
      {
        kind: "para",
        text: "Royal Challengers Bengaluru won the Indian Premier League final on May 31, beating Gujarat Titans in a contest between the two teams that had defined this season. Indian Express's match report recorded the result, and its separate report on the innings recorded a statistical milestone: the fastest half-century in an IPL final, scored by Virat Kohli.",
      },
      {
        kind: "para",
        text: "The route to the final tells the story better than the result does. Gujarat Titans reached it by scoring 104 through Shubman Gill against Vaibhav Sooryavanshi's 96, Deccan Herald reported on May 29, having been sent there to bat first in a qualifier that RCB had earlier won decisively, Patidar's 254 for five against them on May 26.",
      },
      { kind: "subhead", text: "A season of the same two teams" },
      {
        kind: "para",
        text: "That pattern is the strongest argument for reading this final as a rematch rather than an event. The same matchup decided the qualifier and the final, which in a twenty-team competition is close to unprecedented and suggests that the league stage had already identified a genuine mismatch that the playoffs then confirmed twice.",
      },
      {
        kind: "para",
        text: "Indian Express's own account of the final was framed less around the result than around how the chase was constructed, with a separate column noting that a seam bowler's wobble had done the decisive damage to the Gujarat batters. Either way, the record for a final belongs to Kohli, and the season belongs to a Bengaluru side that finally converted a strong league campaign into a title.",
      },
      {
        kind: "dateline-note",
        text: "Reporting note: this report was compiled retrospectively by NOT SCRIPTED from Indian Express's match coverage of May 31, 2026 and Deccan Herald's qualifier coverage of May 26 and 29. NOT SCRIPTED did not attend the match and does not reproduce any scorecard detail beyond the figures recorded in the cited reports.",
      },
    ],
    sources: [
      {
        name: "Indian Express — Cricket",
        url: "https://indianexpress.com/article/sports/cricket/the-short-story-how-rcb-attack-ran-through-gujarat-titans-in-ipl-final-10717340/",
        date: "2026-05-31",
        type: "publication",
      },
      {
        name: "Indian Express — Cricket",
        url: "https://indianexpress.com/article/sports/cricket/record-alert-virat-kohli-scores-fastest-ipl-half-century-in-final-10717386/",
        date: "2026-05-31",
        type: "publication",
      },
      {
        name: "Indian Express — Cricket",
        url: "https://indianexpress.com/article/sports/cricket/bhuvneshwars-wobble-seam-foxes-gt-batters-ipl-rresurgence-10717323/",
        date: "2026-05-31",
        type: "publication",
      },
      {
        name: "Deccan Herald — Cricket",
        url: "https://www.deccanherald.com/sports/cricket/ipl-2026-vaibhav-sooryavanshis-heroic-96-goes-in-vain-as-shubman-gills-104-powers-gujarat-titans-into-final-4021076",
        date: "2026-05-29",
        type: "publication",
      },
      {
        name: "Deccan Herald — Cricket",
        url: "https://www.deccanherald.com/sports/cricket/ipl-2026-qualifier-1-skipper-patidar-carnage-lifts-rcb-to-massive-2545-against-gujarat-titans-4017149",
        date: "2026-05-26",
        type: "publication",
      },
    ],
    art: {
      alt: "Abstract editorial illustration: a stylised floodlit stadium bowl in deep indigo, with two opposing arcs of light meeting above a central vertical column of gold and a scatter of small raised rectangles suggesting a crowd.",
      caption: "Bengaluru and Gujarat Titans met twice in the IPL 2026 playoffs and split the two matches.",
      credit: "Illustration: NOT SCRIPTED",
    },
  },
];
