import type { Author } from "./types";

export const AUTHORS: Author[] = [
  {
    id: "a-nandini-rao",
    name: "Nandini Rao",
    role: "Chief Correspondent",
    desk: "Politics",
    bio: "Covers Parliament, party machinery and electoral data. Previously on the national political desk for a metro daily.",
    location: "New Delhi",
  },
  {
    id: "a-imran-khan",
    name: "Imran Khan",
    role: "Senior Reporter",
    desk: "Politics",
    bio: "State politics and administrative reform, with a focus on how policy reaches the district.",
    location: "New Delhi",
  },
  {
    id: "a-meera-iyengar",
    name: "Meera Iyengar",
    role: "Politics Editor",
    desk: "Politics",
    bio: "Edits the politics desk and writes the weekly on constitutional and institutional questions.",
    location: "New Delhi",
  },
  {
    id: "a-rohit-banerjee",
    name: "Rohit Banerjee",
    role: "Economics Correspondent",
    desk: "Business",
    bio: "Macroeconomics, public finance and the quarterly numbers. Reads the budget documents for pleasure.",
    location: "Mumbai",
  },
  {
    id: "a-divya-raghavan",
    name: "Divya Raghavan",
    role: "Markets Reporter",
    desk: "Business",
    bio: "Equities, debt and capital markets, with a standing interest in what retail investors are actually holding.",
    location: "Mumbai",
  },
  {
    id: "a-karan-malhotra",
    name: "Karan Malhotra",
    role: "Business Editor",
    desk: "Business",
    bio: "Runs the business desk. Writes on corporate governance and the Indian conglomerate.",
    location: "Mumbai",
  },
  {
    id: "a-priya-shankar",
    name: "Priya Shankar",
    role: "Bengaluru Correspondent",
    desk: "Bengaluru & Karnataka",
    bio: "The city's infrastructure, water and traffic problems, and the politics of fixing them.",
    location: "Bengaluru",
  },
  {
    id: "a-vikram-nadkarni",
    name: "Vikram Nadkarni",
    role: "Karnataka Correspondent",
    desk: "Bengaluru & Karnataka",
    bio: "State finance, revenue and the districts outside the ring road.",
    location: "Bengaluru",
  },
  {
    id: "a-ananya-deshpande",
    name: "Ananya Deshpande",
    role: "City Editor",
    desk: "Bengaluru & Karnataka",
    bio: "Edits the Bengaluru desk. Files on housing, mobility and the everyday city.",
    location: "Bengaluru",
  },
  {
    id: "a-sanjay-mehra",
    name: "Sanjay Mehra",
    role: "Technology Editor",
    desk: "Technology",
    bio: "Semiconductors, AI infrastructure and Indian tech policy. Believes every deck needs a supply-chain slide.",
    location: "Bengaluru",
  },
  {
    id: "a-farah-qureshi",
    name: "Farah Qureshi",
    role: "Technology Reporter",
    desk: "Technology",
    bio: "Startups, platforms and the labour behind the product.",
    location: "Bengaluru",
  },
  {
    id: "a-rahul-nambiar",
    name: "Rahul Nambiar",
    role: "Cyber and Security Reporter",
    desk: "Technology",
    bio: "Critical infrastructure, cyber policy and space systems.",
    location: "Hyderabad",
  },
  {
    id: "a-helena-costa",
    name: "Helena Costa",
    role: "World Affairs Correspondent",
    desk: "World",
    bio: "Europe and Latin America, with a long record of filing from border regions.",
    location: "Lisbon",
  },
  {
    id: "a-marcus-oyelaran",
    name: "Marcus Oyelaran",
    role: "World Editor",
    desk: "World",
    bio: "Edits the world desk. Previously reported across Africa and the Gulf.",
    location: "London",
  },
  {
    id: "a-yuki-tanaka",
    name: "Yuki Tanaka",
    role: "Asia Correspondent",
    desk: "World",
    bio: "East and Southeast Asia, trade and supply chains.",
    location: "Singapore",
  },
  {
    id: "a-dmitri-volkov",
    name: "Dmitri Volkov",
    role: "Geopolitics Analyst",
    desk: "Geopolitics",
    bio: "Great-power competition, defence procurement and India's neighbourhood.",
    location: "New Delhi",
  },
  {
    id: "a-leila-haddad",
    name: "Leila Haddad",
    role: "Geopolitics Correspondent",
    desk: "Geopolitics",
    bio: "Energy security, shipping chokepoints and the Gulf.",
    location: "Dubai",
  },
  {
    id: "a-gaurav-menon",
    name: "Gaurav Menon",
    role: "Science Correspondent",
    desk: "Science",
    bio: "Space, physics and the institutions behind them.",
    location: "Bengaluru",
  },
  {
    id: "a-nadia-rahman",
    name: "Nadia Rahman",
    role: "Health & Science Reporter",
    desk: "Science",
    bio: "Public health, clinical research and the long tail of epidemiology.",
    location: "Hyderabad",
  },
  {
    id: "a-tara-iyengar",
    name: "Tara Iyengar",
    role: "Environment Editor",
    desk: "Environment",
    bio: "Edits the environment desk. Tracks air quality data, riverine pollution and the energy transition.",
    location: "New Delhi",
  },
  {
    id: "a-abhishek-nair",
    name: "Abhishek Nair",
    role: "Environment Reporter",
    desk: "Environment",
    bio: "Forests, wetlands, heat and climate adaptation in the Indian states.",
    location: "Bengaluru",
  },
  {
    id: "a-revathi-kumar",
    name: "Revathi Kumar",
    role: "Culture Writer",
    desk: "Culture",
    bio: "Film, publishing and the economics of the Indian screen.",
    location: "Bengaluru",
  },
  {
    id: "a-samir-azad",
    name: "Samir Azad",
    role: "Culture Correspondent",
    desk: "Culture",
    bio: "Music, museums and language politics.",
    location: "Mumbai",
  },
  {
    id: "a-deepti-mishra",
    name: "Deepti Mishra",
    role: "Lifestyle Editor",
    desk: "Lifestyle",
    bio: "Edits lifestyle and food. Keeps a spreadsheet of what things used to cost.",
    location: "Mumbai",
  },
  {
    id: "a-ashwin-jois",
    name: "Ashwin Jois",
    role: "Lifestyle Reporter",
    desk: "Lifestyle",
    bio: "Health, housing and travel that has nothing to do with influencers.",
    location: "Bengaluru",
  },
  {
    id: "a-vinay-karnik",
    name: "Vinay Karnik",
    role: "Sports Editor",
    desk: "Sports",
    bio: "Edits the sports desk. Cricket first, everything else through the cricket desk.",
    location: "Mumbai",
  },
  {
    id: "a-anjali-dsouza",
    name: "Anjali D'Souza",
    role: "Sports Reporter",
    desk: "Sports",
    bio: "Multi-sport and the business of Indian sport, from central contracts to grassroots funding.",
    location: "Bengaluru",
  },
  {
    id: "a-not-scripted-desk",
    name: "NOT SCRIPTED Desk",
    role: "Reference Desk",
    desk: "Archive",
    bio: "The reference desk maintains NOT SCRIPTED's archive: it verifies events against primary sources, records the source metadata and marks retrospective coverage clearly.",
    location: "Bengaluru",
  },
];

export const AUTHOR_MAP: Record<string, Author> = Object.fromEntries(
  AUTHORS.map((a) => [a.id, a]),
);