import type { ArticlePhoto } from "./types";

export const PHOTOS: Record<string, ArticlePhoto> = {
  "union-budget-2026-27-capex-deficit-targets": {
    base: "/img/articles/w/union-budget-2026-27-capex-deficit-targets",
    srcset: "/img/articles/w/union-budget-2026-27-capex-deficit-targets-400.jpg 400w, /img/articles/w/union-budget-2026-27-capex-deficit-targets-800.jpg 800w, /img/articles/w/union-budget-2026-27-capex-deficit-targets-1400.jpg 1400w",
    width: 1400,
    height: 726,
    caption: "The Parliament House building in New Delhi, where the Union Budget is presented each February.",
    alt: "The Parliament House building in New Delhi, where the Union Budget is presented each February.",
    author: "This image was produced by me, David Castor ( user:dcastor ). The pictures I submit to the Wikipedia Project are released to the public domain. This gives you the right to use them in any way you like, without any kind of notification. This said, I would still appreciate to be mentioned as the originator whenever you think it complies well with your use of the picture. A message to me about how it has been used would also be welcome. You are obviously not required to respond to these wishes of mine, just in a friendly manner encouraged to. (All my photos are placed in Category:Images by David Castor or a subcategory thereof.)",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Sansad_Bhavan-1.jpg",
    sourceTitle: "",
  },
  "macroeconomic-framework-statement-2026-growth-numbers": {
    base: "/img/articles/w/macroeconomic-framework-statement-2026-growth-numbers",
    srcset: "/img/articles/w/macroeconomic-framework-statement-2026-growth-numbers-400.jpg 400w, /img/articles/w/macroeconomic-framework-statement-2026-growth-numbers-800.jpg 800w, /img/articles/w/macroeconomic-framework-statement-2026-growth-numbers-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "North Block on Raisina Hill, New Delhi, which houses the Union Finance Ministry.",
    alt: "North Block on Raisina Hill, New Delhi, which houses the Union Finance Ministry.",
    author: "Pinakpani",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/North_Block%2C_Raisina_Hill%2C_New_Delhi_02.jpg",
    sourceTitle: "",
  },
  "former-finance-secretary-challenges-india-gdp-nominal-growth-figure": {
    base: "/img/articles/w/former-finance-secretary-challenges-india-gdp-nominal-growth-figure",
    srcset: "/img/articles/w/former-finance-secretary-challenges-india-gdp-nominal-growth-figure-400.jpg 400w, /img/articles/w/former-finance-secretary-challenges-india-gdp-nominal-growth-figure-800.jpg 800w, /img/articles/w/former-finance-secretary-challenges-india-gdp-nominal-growth-figure-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "North Block, Raisina Hill, New Delhi, seat of the Finance Ministry.",
    alt: "North Block, Raisina Hill, New Delhi, seat of the Finance Ministry.",
    author: "Pinakpani",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/North_Block%2C_Raisina_Hill%2C_New_Delhi_02.jpg",
    sourceTitle: "",
  },
  "march-2026-indian-markets-selloff-analysis-oil-rupee-fpi": {
    base: "/img/articles/w/march-2026-indian-markets-selloff-analysis-oil-rupee-fpi",
    srcset: "/img/articles/w/march-2026-indian-markets-selloff-analysis-oil-rupee-fpi-400.jpg 400w, /img/articles/w/march-2026-indian-markets-selloff-analysis-oil-rupee-fpi-800.jpg 800w, /img/articles/w/march-2026-indian-markets-selloff-analysis-oil-rupee-fpi-1400.jpg 1400w",
    width: 1400,
    height: 1172,
    caption: "The Bombay Stock Exchange building in Dalal Street, Mumbai.",
    alt: "The Bombay Stock Exchange building in Dalal Street, Mumbai.",
    author: "Niyantha Shekhar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/BSE_-_Bombay_Stock_Exchange_Building.jpg",
    sourceTitle: "",
  },
  "jio-platforms-ipo-october-listing-explainer": {
    base: "/img/articles/w/jio-platforms-ipo-october-listing-explainer",
    srcset: "/img/articles/w/jio-platforms-ipo-october-listing-explainer-400.jpg 400w, /img/articles/w/jio-platforms-ipo-october-listing-explainer-800.jpg 800w, /img/articles/w/jio-platforms-ipo-october-listing-explainer-1400.jpg 1400w",
    width: 1400,
    height: 1867,
    caption: "The Bombay Stock Exchange, the venue where a Jio Platforms listing would be marked.",
    alt: "The Bombay Stock Exchange, the venue where a Jio Platforms listing would be marked.",
    author: "AroundTheGlobe",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Bombay_Stock_Exchange_2.jpg",
    sourceTitle: "",
  },
  "rbi-february-2026-policy-repo-rate-hold": {
    base: "/img/articles/w/rbi-february-2026-policy-repo-rate-hold",
    srcset: "/img/articles/w/rbi-february-2026-policy-repo-rate-hold-400.jpg 400w, /img/articles/w/rbi-february-2026-policy-repo-rate-hold-800.jpg 800w, /img/articles/w/rbi-february-2026-policy-repo-rate-hold-1400.jpg 1400w",
    width: 1400,
    height: 2108,
    caption: "An entrance to the Reserve Bank of India in Kolkata. The central office is in Mumbai.",
    alt: "An entrance to the Reserve Bank of India in Kolkata. The central office is in Mumbai.",
    author: "Biswarup Ganguly",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Entrance_-_Reserve_Bank_of_India_-_8_Council_House_Street_-_Kolkata_2014-09-29_7501.JPG",
    sourceTitle: "",
  },
  "rbi-holds-repo-rate-5-25-april-2026-policy": {
    base: "/img/articles/w/rbi-holds-repo-rate-5-25-april-2026-policy",
    srcset: "/img/articles/w/rbi-holds-repo-rate-5-25-april-2026-policy-400.jpg 400w, /img/articles/w/rbi-holds-repo-rate-5-25-april-2026-policy-800.jpg 800w, /img/articles/w/rbi-holds-repo-rate-5-25-april-2026-policy-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "The Reserve Bank of India building in Mumbai, the central bank that sets the repo rate.",
    alt: "The Reserve Bank of India building in Mumbai, the central bank that sets the repo rate.",
    author: "Anurag Vijay 03",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Reserve_Bank_Of_India_-_RBI_Mumbai.jpg",
    sourceTitle: "",
  },
  "rbi-june-2026-policy-decision-explained": {
    base: "/img/articles/w/rbi-june-2026-policy-decision-explained",
    srcset: "/img/articles/w/rbi-june-2026-policy-decision-explained-400.jpg 400w, /img/articles/w/rbi-june-2026-policy-decision-explained-800.jpg 800w, /img/articles/w/rbi-june-2026-policy-decision-explained-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A Reserve Bank of India office in Nagpur. Monetary policy is set at the central office in Mumbai.",
    alt: "A Reserve Bank of India office in Nagpur. Monetary policy is set at the central office in Mumbai.",
    author: "Gppande",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Nagpur_Reserve_Bank.JPG",
    sourceTitle: "",
  },
  "why-indias-gdp-growth-number-is-argued-about-base-year-explainer": {
    base: "/img/articles/w/why-indias-gdp-growth-number-is-argued-about-base-year-explainer",
    srcset: "/img/articles/w/why-indias-gdp-growth-number-is-argued-about-base-year-explainer-400.jpg 400w, /img/articles/w/why-indias-gdp-growth-number-is-argued-about-base-year-explainer-800.jpg 800w, /img/articles/w/why-indias-gdp-growth-number-is-argued-about-base-year-explainer-1400.jpg 1400w",
    width: 1400,
    height: 1048,
    caption: "The Reserve Bank of India building in Mumbai.",
    alt: "The Reserve Bank of India building in Mumbai.",
    author: "Sailko",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Mumbai%2C_reserve_bank_of_india_01.jpg",
    sourceTitle: "",
  },
  "rupee-record-lows-capital-outflows-rbi": {
    base: "/img/articles/w/rupee-record-lows-capital-outflows-rbi",
    srcset: "/img/articles/w/rupee-record-lows-capital-outflows-rbi-400.jpg 400w, /img/articles/w/rupee-record-lows-capital-outflows-rbi-800.jpg 800w, /img/articles/w/rupee-record-lows-capital-outflows-rbi-1400.jpg 1400w",
    width: 1400,
    height: 2489,
    caption: "Indian currency notes in circulation.",
    alt: "Indian currency notes in circulation.",
    author: "Prasanth 05",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Indian_currency%E2%80%A6.jpg",
    sourceTitle: "",
  },
  "income-tax-act-2025-takes-effect-first-april-2026": {
    base: "/img/articles/w/income-tax-act-2025-takes-effect-first-april-2026",
    srcset: "/img/articles/w/income-tax-act-2025-takes-effect-first-april-2026-400.jpg 400w, /img/articles/w/income-tax-act-2025-takes-effect-first-april-2026-800.jpg 800w, /img/articles/w/income-tax-act-2025-takes-effect-first-april-2026-1400.jpg 1400w",
    width: 1400,
    height: 1867,
    caption: "The Income Tax Department building in Pune, one of the offices administering the new Income-tax Act.",
    alt: "The Income Tax Department building in Pune, one of the offices administering the new Income-tax Act.",
    author: "DesiBoy101",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Aaykar_Bhavan%2C_Income_Tax_Department%2C_Pune.jpg",
    sourceTitle: "",
  },
  "india-retail-inflation-hits-4-38-percent-in-june": {
    base: "/img/articles/w/india-retail-inflation-hits-4-38-percent-in-june",
    srcset: "/img/articles/w/india-retail-inflation-hits-4-38-percent-in-june-400.jpg 400w, /img/articles/w/india-retail-inflation-hits-4-38-percent-in-june-800.jpg 800w, /img/articles/w/india-retail-inflation-hits-4-38-percent-in-june-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A vegetable market in Hyderabad. Food weights most heavily in India's retail inflation basket.",
    alt: "A vegetable market in Hyderabad. Food weights most heavily in India's retail inflation basket.",
    author: "Iijjccoo at Dutch Wikipedia",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Market_Hyderabad.jpg",
    sourceTitle: "",
  },
  "march-inflation-3-40-percent-what-it-means-households": {
    base: "/img/articles/w/march-inflation-3-40-percent-what-it-means-households",
    srcset: "/img/articles/w/march-inflation-3-40-percent-what-it-means-households-400.jpg 400w, /img/articles/w/march-inflation-3-40-percent-what-it-means-households-800.jpg 800w, /img/articles/w/march-inflation-3-40-percent-what-it-means-households-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "An Indian household kitchen, where inflation is actually felt.",
    alt: "An Indian household kitchen, where inflation is actually felt.",
    author: "Adrian Sulc",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Indian_Cuisine_in_household.jpg",
    sourceTitle: "",
  },
  "petrol-diesel-hike-three-rupees-west-asia-costs": {
    base: "/img/articles/w/petrol-diesel-hike-three-rupees-west-asia-costs",
    srcset: "/img/articles/w/petrol-diesel-hike-three-rupees-west-asia-costs-400.jpg 400w, /img/articles/w/petrol-diesel-hike-three-rupees-west-asia-costs-800.jpg 800w, /img/articles/w/petrol-diesel-hike-three-rupees-west-asia-costs-1400.jpg 1400w",
    width: 1400,
    height: 840,
    caption: "An Indian Oil petrol station in Sikkim.",
    alt: "An Indian Oil petrol station in Sikkim.",
    author: "Bernard Gagnon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Indian_Oil_petrol_station%2C_Rangpo%2C_Sikkim.jpg",
    sourceTitle: "",
  },
  "domestic-lpg-prices-unchanged-commercial-cylinder-hike-january-2026": {
    base: "/img/articles/w/domestic-lpg-prices-unchanged-commercial-cylinder-hike-january-2026",
    srcset: "/img/articles/w/domestic-lpg-prices-unchanged-commercial-cylinder-hike-january-2026-400.jpg 400w, /img/articles/w/domestic-lpg-prices-unchanged-commercial-cylinder-hike-january-2026-800.jpg 800w, /img/articles/w/domestic-lpg-prices-unchanged-commercial-cylinder-hike-january-2026-1400.jpg 1400w",
    width: 1400,
    height: 1320,
    caption: "An LPG cylinder in Tamil Nadu, the domestic cooking gas most Indian households buy.",
    alt: "An LPG cylinder in Tamil Nadu, the domestic cooking gas most Indian households buy.",
    author: "à®¤à®•à®µà®²à¯à®´à®µà®©à¯",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Cylinder%2Cgas%2C_Indane%2CTamil_Nadu452.jpeg",
    sourceTitle: "",
  },
  "india-fuel-logistics-hormuz-shock-not-supply": {
    base: "/img/articles/w/india-fuel-logistics-hormuz-shock-not-supply",
    srcset: "/img/articles/w/india-fuel-logistics-hormuz-shock-not-supply-400.jpg 400w, /img/articles/w/india-fuel-logistics-hormuz-shock-not-supply-800.jpg 800w",
    width: 800,
    height: 1035,
    caption: "The Essar Oil Refinery. India imports most of its crude, which is why a chokepoint closure moves fuel prices at the pump.",
    alt: "The Essar Oil Refinery. India imports most of its crude, which is why a chokepoint closure moves fuel prices at the pump.",
    author: "Good, Jeffrey E.",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/AN_OPERATIONAL_MODEL_OF_CRITICAL_SUPPLY_CHAIN_FOR_THE_U.S._VIRGIN_ISLANDS_(IA_anoperationalmod1094563455).pdf",
    sourceTitle: "",
  },
  "india-oil-import-exposure-strait-hormuz-data": {
    base: "/img/articles/w/india-oil-import-exposure-strait-hormuz-data",
    srcset: "/img/articles/w/india-oil-import-exposure-strait-hormuz-data-400.jpg 400w, /img/articles/w/india-oil-import-exposure-strait-hormuz-data-800.jpg 800w, /img/articles/w/india-oil-import-exposure-strait-hormuz-data-1400.jpg 1400w",
    width: 1400,
    height: 637,
    caption: "The Essar Oil Refinery at Vadinar, Gujarat.",
    alt: "The Essar Oil Refinery at Vadinar, Gujarat.",
    author: "Abhisek Sarda",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/The_Essar_Oil_Refinery.jpg",
    sourceTitle: "",
  },
  "gold-silver-correction-and-what-history-says": {
    base: "/img/articles/w/gold-silver-correction-and-what-history-says",
    srcset: "/img/articles/w/gold-silver-correction-and-what-history-says-400.jpg 400w, /img/articles/w/gold-silver-correction-and-what-history-says-800.jpg 800w, /img/articles/w/gold-silver-correction-and-what-history-says-1400.jpg 1400w",
    width: 1400,
    height: 933,
    caption: "Gold bullion, the asset whose correction this piece examines.",
    alt: "Gold bullion, the asset whose correction this piece examines.",
    author: "Szaaman",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Gold_bullion_1.jpg",
    sourceTitle: "",
  },
  "tcs-q1-fy27-profit-up-margin-under-pressure": {
    base: "/img/articles/w/tcs-q1-fy27-profit-up-margin-under-pressure",
    srcset: "/img/articles/w/tcs-q1-fy27-profit-up-margin-under-pressure-400.jpg 400w, /img/articles/w/tcs-q1-fy27-profit-up-margin-under-pressure-800.jpg 800w, /img/articles/w/tcs-q1-fy27-profit-up-margin-under-pressure-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "The Tata Consultancy Services campus at Madhapur in Hyderabad. TCS is headquartered in Chennai.",
    alt: "The Tata Consultancy Services campus at Madhapur in Hyderabad. TCS is headquartered in Chennai.",
    author: "Veera.sj",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Tata_Consultancy_Services_Madhapur_Hyderabad.jpg",
    sourceTitle: "",
  },
  "supreme-court-upholds-sir-orders-ec-to-report-deletions": {
    base: "/img/articles/w/supreme-court-upholds-sir-orders-ec-to-report-deletions",
    srcset: "/img/articles/w/supreme-court-upholds-sir-orders-ec-to-report-deletions-400.jpg 400w, /img/articles/w/supreme-court-upholds-sir-orders-ec-to-report-deletions-800.jpg 800w, /img/articles/w/supreme-court-upholds-sir-orders-ec-to-report-deletions-1400.jpg 1400w",
    width: 1400,
    height: 1867,
    caption: "Inside the Supreme Court of India in New Delhi, which upheld the electoral roll exercise.",
    alt: "Inside the Supreme Court of India in New Delhi, which upheld the electoral roll exercise.",
    author: "Pinakpani",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Inside_the_Supreme_Court_of_India._10.jpg",
    sourceTitle: "",
  },
  "bengaluru-civic-polls-supreme-court-august-deadline": {
    base: "/img/articles/w/bengaluru-civic-polls-supreme-court-august-deadline",
    srcset: "/img/articles/w/bengaluru-civic-polls-supreme-court-august-deadline-400.jpg 400w, /img/articles/w/bengaluru-civic-polls-supreme-court-august-deadline-800.jpg 800w, /img/articles/w/bengaluru-civic-polls-supreme-court-august-deadline-1400.jpg 1400w",
    width: 1400,
    height: 1867,
    caption: "Inside the Supreme Court of India, which set the deadline for the Bengaluru civic polls.",
    alt: "Inside the Supreme Court of India, which set the deadline for the Bengaluru civic polls.",
    author: "Pinakpani",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Inside_the_Supreme_Court_of_India._10.jpg",
    sourceTitle: "",
  },
  "neet-ug-2026-cancelled-what-the-reporting-shows": {
    base: "/img/articles/w/neet-ug-2026-cancelled-what-the-reporting-shows",
    srcset: "/img/articles/w/neet-ug-2026-cancelled-what-the-reporting-shows-400.jpg 400w, /img/articles/w/neet-ug-2026-cancelled-what-the-reporting-shows-800.jpg 800w, /img/articles/w/neet-ug-2026-cancelled-what-the-reporting-shows-1400.jpg 1400w",
    width: 1400,
    height: 960,
    caption: "An examination script. The NEET-UG 2026 test was cancelled and the question of rescheduling became a national argument.",
    alt: "An examination script. The NEET-UG 2026 test was cancelled and the question of rescheduling became a national argument.",
    author: "KF",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Test_(student_assessment).jpeg",
    sourceTitle: "",
  },
  "dhurandhar-the-revenge-opens-to-records-march-2026": {
    base: "/img/articles/w/dhurandhar-the-revenge-opens-to-records-march-2026",
    srcset: "/img/articles/w/dhurandhar-the-revenge-opens-to-records-march-2026-400.jpg 400w, /img/articles/w/dhurandhar-the-revenge-opens-to-records-march-2026-800.jpg 800w, /img/articles/w/dhurandhar-the-revenge-opens-to-records-march-2026-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A multiplex cinema in Mumbai, where an Indian release earns most of its first weekend.",
    alt: "A multiplex cinema in Mumbai, where an Indian release earns most of its first weekend.",
    author: "Nicke.me",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Metro_Cinema%2C_Mumbai.JPG",
    sourceTitle: "",
  },
  "karuppu-box-office-tamil-nine-month-drought": {
    base: "/img/articles/w/karuppu-box-office-tamil-nine-month-drought",
    srcset: "/img/articles/w/karuppu-box-office-tamil-nine-month-drought-400.jpg 400w, /img/articles/w/karuppu-box-office-tamil-nine-month-drought-800.jpg 800w, /img/articles/w/karuppu-box-office-tamil-nine-month-drought-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A theatre in Chennai, the city that opens Tamil releases first.",
    alt: "A theatre in Chennai, the city that opens Tamil releases first.",
    author: "L.vivian.richard at English Wikipedia",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Madras_museum_theatre_in_October_2007.jpg",
    sourceTitle: "",
  },
  "siddaramaiah-resigns-shivakumar-karnataka-chief-minister": {
    base: "/img/articles/w/siddaramaiah-resigns-shivakumar-karnataka-chief-minister",
    srcset: "/img/articles/w/siddaramaiah-resigns-shivakumar-karnataka-chief-minister-400.jpg 400w, /img/articles/w/siddaramaiah-resigns-shivakumar-karnataka-chief-minister-800.jpg 800w, /img/articles/w/siddaramaiah-resigns-shivakumar-karnataka-chief-minister-1400.jpg 1400w",
    width: 1400,
    height: 959,
    caption: "Vidhana Soudha in Bengaluru, where the Karnataka government is formed.",
    alt: "Vidhana Soudha in Bengaluru, where the Karnataka government is formed.",
    author: "Rameshng at Malayalam Wikipedia",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Vidhan_Soudha_Bangalore_Front_view.JPG",
    sourceTitle: "",
  },
  "dk-shivakumar-sworn-in-as-karnataka-chief-minister": {
    base: "/img/articles/w/dk-shivakumar-sworn-in-as-karnataka-chief-minister",
    srcset: "/img/articles/w/dk-shivakumar-sworn-in-as-karnataka-chief-minister-400.jpg 400w, /img/articles/w/dk-shivakumar-sworn-in-as-karnataka-chief-minister-800.jpg 800w, /img/articles/w/dk-shivakumar-sworn-in-as-karnataka-chief-minister-1400.jpg 1400w",
    width: 1400,
    height: 914,
    caption: "Vidhana Soudha in Bengaluru, the seat of the Karnataka legislature.",
    alt: "Vidhana Soudha in Bengaluru, the seat of the Karnataka legislature.",
    author: "Rajesh Vadlamani",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Vidhan_Sodha_HDR.jpg",
    sourceTitle: "",
  },
  "karnataka-governor-gehlot-address-walkout-joint-session": {
    base: "/img/articles/w/karnataka-governor-gehlot-address-walkout-joint-session",
    srcset: "/img/articles/w/karnataka-governor-gehlot-address-walkout-joint-session-400.jpg 400w, /img/articles/w/karnataka-governor-gehlot-address-walkout-joint-session-800.jpg 800w, /img/articles/w/karnataka-governor-gehlot-address-walkout-joint-session-1400.jpg 1400w",
    width: 1400,
    height: 1867,
    caption: "Raj Bhavan in Bengaluru, the Governor's residence, where the joint session is held.",
    alt: "Raj Bhavan in Bengaluru, the Governor's residence, where the joint session is held.",
    author: "Gpkp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Independence_day_at_Raj_Bhavan%2C_Bangalore_(2025)_25.jpg",
    sourceTitle: "",
  },
  "five-states-three-governments-after-2026-verdicts": {
    base: "/img/articles/w/five-states-three-governments-after-2026-verdicts",
    srcset: "/img/articles/w/five-states-three-governments-after-2026-verdicts-400.jpg 400w, /img/articles/w/five-states-three-governments-after-2026-verdicts-800.jpg 800w, /img/articles/w/five-states-three-governments-after-2026-verdicts-1400.jpg 1400w",
    width: 1400,
    height: 959,
    caption: "Vidhana Soudha in Bengaluru, one of the states whose government changed hands.",
    alt: "Vidhana Soudha in Bengaluru, one of the states whose government changed hands.",
    author: "Rameshng at Malayalam Wikipedia",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Vidhan_Soudha_Bangalore_Front_view.JPG",
    sourceTitle: "",
  },
  "bengaluru-green-line-metro-halted-by-power-breakdown": {
    base: "/img/articles/w/bengaluru-green-line-metro-halted-by-power-breakdown",
    srcset: "/img/articles/w/bengaluru-green-line-metro-halted-by-power-breakdown-400.jpg 400w, /img/articles/w/bengaluru-green-line-metro-halted-by-power-breakdown-800.jpg 800w, /img/articles/w/bengaluru-green-line-metro-halted-by-power-breakdown-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A Namma Metro train in Bengaluru, the network whose Green Line was suspended.",
    alt: "A Namma Metro train in Bengaluru, the network whose Green Line was suspended.",
    author: "Fly2Blue",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/Namma_metro.jpg",
    sourceTitle: "",
  },
  "namma-metro-blue-line-solar-corridor-study": {
    base: "/img/articles/w/namma-metro-blue-line-solar-corridor-study",
    srcset: "/img/articles/w/namma-metro-blue-line-solar-corridor-study-400.jpg 400w, /img/articles/w/namma-metro-blue-line-solar-corridor-study-800.jpg 800w, /img/articles/w/namma-metro-blue-line-solar-corridor-study-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A route map of the Namma Metro in Bengaluru.",
    alt: "A route map of the Namma Metro in Bengaluru.",
    author: "Veera.sj",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    sourceUrl: "https://commons.wikimedia.org/wiki/Namma_Metro_Bengaluru_Linear_Map_Blueprint_-_English.JPG",
    sourceTitle: "",
  },
  "bengaluru-bescom-planned-power-shutdowns-january-2026": {
    base: "/img/articles/w/bengaluru-bescom-planned-power-shutdowns-january-2026",
    srcset: "/img/articles/w/bengaluru-bescom-planned-power-shutdowns-january-2026-400.jpg 400w, /img/articles/w/bengaluru-bescom-planned-power-shutdowns-january-2026-800.jpg 800w, /img/articles/w/bengaluru-bescom-planned-power-shutdowns-january-2026-1400.jpg 1400w",
    width: 1400,
    height: 187,
    caption: "The Whitefield area of Bengaluru, one of the districts BESCOM schedules outages in.",
    alt: "The Whitefield area of Bengaluru, one of the districts BESCOM schedules outages in.",
    author: "Doc.aneesh",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Whitefield_Panorama.jpg",
    sourceTitle: "",
  },
  "bengaluru-east-taluka-groundwater-extraction-378-percent": {
    base: "/img/articles/w/bengaluru-east-taluka-groundwater-extraction-378-percent",
    srcset: "/img/articles/w/bengaluru-east-taluka-groundwater-extraction-378-percent-400.jpg 400w, /img/articles/w/bengaluru-east-taluka-groundwater-extraction-378-percent-800.jpg 800w, /img/articles/w/bengaluru-east-taluka-groundwater-extraction-378-percent-1400.jpg 1400w",
    width: 1400,
    height: 743,
    caption: "Bellandur lake in Bengaluru viewed from a high-rise. The east taluka's extraction figures are drawn from wells like these.",
    alt: "Bellandur lake in Bengaluru viewed from a high-rise. The east taluka's extraction figures are drawn from wells like these.",
    author: "Amol.Gaitonde",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Humming_Bird_Suites_and_Bellandur_lake_seen_from_Top_of_Utopia_8-15-2010_1-42-47_PM.JPG",
    sourceTitle: "",
  },
  "anthropic-bengaluru-office-india-partnerships": {
    base: "/img/articles/w/anthropic-bengaluru-office-india-partnerships",
    srcset: "/img/articles/w/anthropic-bengaluru-office-india-partnerships-400.jpg 400w, /img/articles/w/anthropic-bengaluru-office-india-partnerships-800.jpg 800w, /img/articles/w/anthropic-bengaluru-office-india-partnerships-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "UB City in Bengaluru, the business district where the office was announced.",
    alt: "UB City in Bengaluru, the business district where the office was announced.",
    author: "Prateek Karandikar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/UB_City%2C_Bangalore.JPG",
    sourceTitle: "",
  },
  "cwma-upholds-cauvery-release-to-tamil-nadu": {
    base: "/img/articles/w/cwma-upholds-cauvery-release-to-tamil-nadu",
    srcset: "/img/articles/w/cwma-upholds-cauvery-release-to-tamil-nadu-400.jpg 400w, /img/articles/w/cwma-upholds-cauvery-release-to-tamil-nadu-800.jpg 800w, /img/articles/w/cwma-upholds-cauvery-release-to-tamil-nadu-1400.jpg 1400w",
    width: 1400,
    height: 685,
    caption: "The Krishna Raja Sagara dam, the reservoir at the centre of the Cauvery dispute.",
    alt: "The Krishna Raja Sagara dam, the reservoir at the centre of the Cauvery dispute.",
    author: "Ashwin Kumar from Bangalore, India",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Krishnaraja_Sagar_Dam_(10328848994).jpg",
    sourceTitle: "",
  },
  "tcs-opens-nvidia-backed-ai-lab-in-bengaluru": {
    base: "/img/articles/w/tcs-opens-nvidia-backed-ai-lab-in-bengaluru",
    srcset: "/img/articles/w/tcs-opens-nvidia-backed-ai-lab-in-bengaluru-400.jpg 400w, /img/articles/w/tcs-opens-nvidia-backed-ai-lab-in-bengaluru-800.jpg 800w",
    width: 800,
    height: 1132,
    caption: "Bengaluru's technology campuses, where the lab was opened.",
    alt: "Bengaluru's technology campuses, where the lab was opened.",
    author: "Publications Office of the European Union",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/OJ_C_No._21_of_2012_-_FI_Finnish.pdf",
    sourceTitle: "",
  },
  "modi-inaugurates-bhogapuram-airport-andhra-pradesh": {
    base: "/img/articles/w/modi-inaugurates-bhogapuram-airport-andhra-pradesh",
    srcset: "/img/articles/w/modi-inaugurates-bhogapuram-airport-andhra-pradesh-400.jpg 400w, /img/articles/w/modi-inaugurates-bhogapuram-airport-andhra-pradesh-800.jpg 800w, /img/articles/w/modi-inaugurates-bhogapuram-airport-andhra-pradesh-1400.jpg 1400w",
    width: 1400,
    height: 642,
    caption: "The terminal at Visakhapatnam airport, expanded as part of the Bhogapuram project.",
    alt: "The terminal at Visakhapatnam airport, expanded as part of the Bhogapuram project.",
    author: "Captaingunadeep",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Vizag_airport_terminal_full_view.jpg",
    sourceTitle: "",
  },
  "bhogapuram-airport-commercial-flights-bengaluru-routes": {
    base: "/img/articles/w/bhogapuram-airport-commercial-flights-bengaluru-routes",
    srcset: "/img/articles/w/bhogapuram-airport-commercial-flights-bengaluru-routes-400.jpg 400w, /img/articles/w/bhogapuram-airport-commercial-flights-bengaluru-routes-800.jpg 800w, /img/articles/w/bhogapuram-airport-commercial-flights-bengaluru-routes-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "Visakhapatnam airport, from where the Bengaluru service operates.",
    alt: "Visakhapatnam airport, from where the Bengaluru service operates.",
    author: "Dragon flight1 at en.wikipedia",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Vizagair1.JPG",
    sourceTitle: "",
  },
  "isro-pslv-c62-eos-n1-third-stage-anomaly-launch-failure": {
    base: "/img/articles/w/isro-pslv-c62-eos-n1-third-stage-anomaly-launch-failure",
    srcset: "/img/articles/w/isro-pslv-c62-eos-n1-third-stage-anomaly-launch-failure-400.jpg 400w, /img/articles/w/isro-pslv-c62-eos-n1-third-stage-anomaly-launch-failure-800.jpg 800w, /img/articles/w/isro-pslv-c62-eos-n1-third-stage-anomaly-launch-failure-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A launch vehicle on its pad at Sriharikota.",
    alt: "A launch vehicle on its pad at Sriharikota.",
    author: "Gomathi Jayasankar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Rocket_wings.jpg",
    sourceTitle: "",
  },
  "nasa-reveals-artemis-3-crew-for-moon-mission": {
    base: "/img/articles/w/nasa-reveals-artemis-3-crew-for-moon-mission",
    srcset: "/img/articles/w/nasa-reveals-artemis-3-crew-for-moon-mission-400.jpg 400w, /img/articles/w/nasa-reveals-artemis-3-crew-for-moon-mission-800.jpg 800w, /img/articles/w/nasa-reveals-artemis-3-crew-for-moon-mission-1400.jpg 1400w",
    width: 1400,
    height: 788,
    caption: "An artist's rendering of the Artemis base camp on the Moon.",
    alt: "An artist's rendering of the Artemis base camp on the Moon.",
    author: "NASA",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Artemis_Base_Camp.png",
    sourceTitle: "",
  },
  "nobel-medicine-2026-light-gated-ion-channels-optogenetics": {
    base: "/img/articles/w/nobel-medicine-2026-light-gated-ion-channels-optogenetics",
    srcset: "/img/articles/w/nobel-medicine-2026-light-gated-ion-channels-optogenetics-400.jpg 400w, /img/articles/w/nobel-medicine-2026-light-gated-ion-channels-optogenetics-800.jpg 800w, /img/articles/w/nobel-medicine-2026-light-gated-ion-channels-optogenetics-1400.jpg 1400w",
    width: 1400,
    height: 2074,
    caption: "The Nobel Prize medals awarded by the Swedish Academy.",
    alt: "The Nobel Prize medals awarded by the Swedish Academy.",
    author: "Unknown author Unknown author",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/PSM_V70_D094_Nobel_prize_medals.jpg",
    sourceTitle: "",
  },
  "coal-plant-so2-emissions-deaths-iit-delhi-study": {
    base: "/img/articles/w/coal-plant-so2-emissions-deaths-iit-delhi-study",
    srcset: "/img/articles/w/coal-plant-so2-emissions-deaths-iit-delhi-study-400.jpg 400w, /img/articles/w/coal-plant-so2-emissions-deaths-iit-delhi-study-800.jpg 800w, /img/articles/w/coal-plant-so2-emissions-deaths-iit-delhi-study-1400.jpg 1400w",
    width: 1400,
    height: 956,
    caption: "The Suratgarh Super Thermal Power Plant in Rajasthan, the kind of installation the emissions study modelled.",
    alt: "The Suratgarh Super Thermal Power Plant in Rajasthan, the kind of installation the emissions study modelled.",
    author: "Ramilarora",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Suratgarh_Super_Thermal_Power_Plant.JPG",
    sourceTitle: "",
  },
  "kevda-fossil-leaves-push-assam-record-back": {
    base: "/img/articles/w/kevda-fossil-leaves-push-assam-record-back",
    srcset: "/img/articles/w/kevda-fossil-leaves-push-assam-record-back-400.jpg 400w, /img/articles/w/kevda-fossil-leaves-push-assam-record-back-800.jpg 800w, /img/articles/w/kevda-fossil-leaves-push-assam-record-back-1400.jpg 1400w",
    width: 1400,
    height: 1398,
    caption: "A fossil leaf of the kevda family. The Assam find pushed the group's record back by tens of millions of years.",
    alt: "A fossil leaf of the kevda family. The Assam find pushed the group's record back by tens of millions of years.",
    author: "Amaltheus",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/Fossil-leaf_Taxodium_dubium_Tertiary_Germany.jpg",
    sourceTitle: "",
  },
  "pax-silica-india-invitation-critical-minerals-semiconductor-explainer": {
    base: "/img/articles/w/pax-silica-india-invitation-critical-minerals-semiconductor-explainer",
    srcset: "/img/articles/w/pax-silica-india-invitation-critical-minerals-semiconductor-explainer-400.jpg 400w, /img/articles/w/pax-silica-india-invitation-critical-minerals-semiconductor-explainer-800.jpg 800w, /img/articles/w/pax-silica-india-invitation-critical-minerals-semiconductor-explainer-1400.jpg 1400w",
    width: 1400,
    height: 1400,
    caption: "A 12-inch silicon wafer, the input a silicon coalition would secure.",
    alt: "A 12-inch silicon wafer, the input a silicon coalition would secure.",
    author: "Peellden",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/12-inch_silicon_wafer.jpg",
    sourceTitle: "",
  },
  "ism-2-0-explained-electronics-components-and-data-centres": {
    base: "/img/articles/w/ism-2-0-explained-electronics-components-and-data-centres",
    srcset: "/img/articles/w/ism-2-0-explained-electronics-components-and-data-centres-400.jpg 400w, /img/articles/w/ism-2-0-explained-electronics-components-and-data-centres-800.jpg 800w, /img/articles/w/ism-2-0-explained-electronics-components-and-data-centres-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A printed circuit board, the component the scheme targets.",
    alt: "A printed circuit board, the component the scheme targets.",
    author: "Balurbala",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Printed_Circuit_Board_2.jpg",
    sourceTitle: "",
  },
  "delhi-coldest-january-morning-in-three-years-dense-fog-aqi-very-poor": {
    base: "/img/articles/w/delhi-coldest-january-morning-in-three-years-dense-fog-aqi-very-poor",
    srcset: "/img/articles/w/delhi-coldest-january-morning-in-three-years-dense-fog-aqi-very-poor-400.jpg 400w, /img/articles/w/delhi-coldest-january-morning-in-three-years-dense-fog-aqi-very-poor-800.jpg 800w, /img/articles/w/delhi-coldest-january-morning-in-three-years-dense-fog-aqi-very-poor-1400.jpg 1400w",
    width: 1400,
    height: 938,
    caption: "Smog over Delhi in winter, the condition the cold, foggy morning produced.",
    alt: "Smog over Delhi in winter, the condition the cold, foggy morning produced.",
    author: "wili hybrid Original uploader was Lokantha at en.wikipedia . Later version(s) were uploaded by Nikkul , Thisglad at en.wikipedia .",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Smog_in_the_skies_of_Delhi%2C_India.jpg",
    sourceTitle: "",
  },
  "delhis-worst-july-for-air-in-seven-years": {
    base: "/img/articles/w/delhis-worst-july-for-air-in-seven-years",
    srcset: "/img/articles/w/delhis-worst-july-for-air-in-seven-years-400.jpg 400w, /img/articles/w/delhis-worst-july-for-air-in-seven-years-800.jpg 800w, /img/articles/w/delhis-worst-july-for-air-in-seven-years-1400.jpg 1400w",
    width: 1400,
    height: 1337,
    caption: "Smog across the Gurugram area near Delhi.",
    alt: "Smog across the Gurugram area near Delhi.",
    author: "Saurabh Kumar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Smog_as_visible_in_the_Gurgaon_area_near_Delhi_on_Nov_2016.jpg",
    sourceTitle: "",
  },
  "ntca-tiger-conservation-policy-review-alwar-2026": {
    base: "/img/articles/w/ntca-tiger-conservation-policy-review-alwar-2026",
    srcset: "/img/articles/w/ntca-tiger-conservation-policy-review-alwar-2026-400.jpg 400w, /img/articles/w/ntca-tiger-conservation-policy-review-alwar-2026-800.jpg 800w, /img/articles/w/ntca-tiger-conservation-policy-review-alwar-2026-1400.jpg 1400w",
    width: 1400,
    height: 1323,
    caption: "A tiger in a zoo enclosure. The review concerns wild populations across India's reserves.",
    alt: "A tiger in a zoo enclosure. The review concerns wild populations across India's reserves.",
    author: "Luis Miguel Bugallo SÃ¡nchez (Lmbuga)",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/08-2011_-_Panthera_tigris_tigris._Lanzarote_-_Spain_-_TP08.jpg",
    sourceTitle: "",
  },
  "what-an-early-march-heat-spill-means-for-the-wheat-crop": {
    base: "/img/articles/w/what-an-early-march-heat-spill-means-for-the-wheat-crop",
    srcset: "/img/articles/w/what-an-early-march-heat-spill-means-for-the-wheat-crop-400.jpg 400w, /img/articles/w/what-an-early-march-heat-spill-means-for-the-wheat-crop-800.jpg 800w, /img/articles/w/what-an-early-march-heat-spill-means-for-the-wheat-crop-1400.jpg 1400w",
    width: 1400,
    height: 980,
    caption: "Harvesting wheat in Madhya Pradesh, the crop the early heat was assessed against.",
    alt: "Harvesting wheat in Madhya Pradesh, the crop the early heat was assessed against.",
    author: "Yann Forget",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Woman_harvesting_wheat%2C_Raisen_district%2C_Madhya_Pradesh%2C_India_ggia_version.jpg",
    sourceTitle: "",
  },
  "imd-cuts-southwest-monsoon-forecast-to-ninety-percent": {
    base: "/img/articles/w/imd-cuts-southwest-monsoon-forecast-to-ninety-percent",
    srcset: "/img/articles/w/imd-cuts-southwest-monsoon-forecast-to-ninety-percent-400.jpg 400w, /img/articles/w/imd-cuts-southwest-monsoon-forecast-to-ninety-percent-800.jpg 800w, /img/articles/w/imd-cuts-southwest-monsoon-forecast-to-ninety-percent-1400.jpg 1400w",
    width: 1400,
    height: 933,
    caption: "Monsoon rain over Maharashtra.",
    alt: "Monsoon rain over Maharashtra.",
    author: "Nikhil More",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Monsoon_Maharashtra_India_Rain_Landscape_(1)_02.jpg",
    sourceTitle: "",
  },
  "below-normal-july-rainfall-forecast-by-imd": {
    base: "/img/articles/w/below-normal-july-rainfall-forecast-by-imd",
    srcset: "/img/articles/w/below-normal-july-rainfall-forecast-by-imd-400.jpg 400w, /img/articles/w/below-normal-july-rainfall-forecast-by-imd-800.jpg 800w, /img/articles/w/below-normal-july-rainfall-forecast-by-imd-1400.jpg 1400w",
    width: 1400,
    height: 787,
    caption: "A cloudburst over Delhi, the kind of intense cell a below-normal July can still produce.",
    alt: "A cloudburst over Delhi, the kind of intense cell a below-normal July can still produce.",
    author: "Prateek Rungta from Delhi, India",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Cloudburst_(6150615417).jpg",
    sourceTitle: "",
  },
  "strait-of-hormuz-reopens-after-a-3-5-month-war": {
    base: "/img/articles/w/strait-of-hormuz-reopens-after-a-3-5-month-war",
    srcset: "/img/articles/w/strait-of-hormuz-reopens-after-a-3-5-month-war-400.jpg 400w, /img/articles/w/strait-of-hormuz-reopens-after-a-3-5-month-war-800.jpg 800w, /img/articles/w/strait-of-hormuz-reopens-after-a-3-5-month-war-1400.jpg 1400w",
    width: 1400,
    height: 1400,
    caption: "The Strait of Hormuz photographed from orbit, the chokepoint the war closed.",
    alt: "The Strait of Hormuz photographed from orbit, the chokepoint the war closed.",
    author: "NASA",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/STS004-37-716_-_Strait_of_Hormuz.jpg",
    sourceTitle: "",
  },
  "us-iran-deal-hormuz-reopening-details": {
    base: "/img/articles/w/us-iran-deal-hormuz-reopening-details",
    srcset: "/img/articles/w/us-iran-deal-hormuz-reopening-details-400.jpg 400w, /img/articles/w/us-iran-deal-hormuz-reopening-details-800.jpg 800w, /img/articles/w/us-iran-deal-hormuz-reopening-details-1400.jpg 1400w",
    width: 1400,
    height: 932,
    caption: "The Gulf of Oman and the Strait of Hormuz photographed from the International Space Station at night.",
    alt: "The Gulf of Oman and the Strait of Hormuz photographed from the International Space Station at night.",
    author: "NASA/Tim Kopra",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/ISS-46_Gulf_of_Oman_with_Strait_of_Hormuz_at_night.jpg",
    sourceTitle: "",
  },
  "hormuz-war-risk-premiums-have-doubled": {
    base: "/img/articles/w/hormuz-war-risk-premiums-have-doubled",
    srcset: "/img/articles/w/hormuz-war-risk-premiums-have-doubled-400.jpg 400w, /img/articles/w/hormuz-war-risk-premiums-have-doubled-800.jpg 800w, /img/articles/w/hormuz-war-risk-premiums-have-doubled-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A crude oil tanker at a refinery jetty, the vessel class whose insurance repriced.",
    alt: "A crude oil tanker at a refinery jetty, the vessel class whose insurance repriced.",
    author: "Calistemon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Crude_Oil_Tanker_Pericles_at_BP_Oil_Refinery_Jetty_and_General_Cargo_Ship_Jannes_at_Kwinana_Bulk_Jetty%2C_December_2020_02.jpg",
    sourceTitle: "",
  },
  "oil-risk-premium-iran-hormuz-geopolitics-analysis": {
    base: "/img/articles/w/oil-risk-premium-iran-hormuz-geopolitics-analysis",
    srcset: "/img/articles/w/oil-risk-premium-iran-hormuz-geopolitics-analysis-400.jpg 400w, /img/articles/w/oil-risk-premium-iran-hormuz-geopolitics-analysis-800.jpg 800w, /img/articles/w/oil-risk-premium-iran-hormuz-geopolitics-analysis-1400.jpg 1400w",
    width: 1400,
    height: 922,
    caption: "A product terminal with tankers at Preemraff Lysekil on the Swedish coast, a route outside the Gulf.",
    alt: "A product terminal with tankers at Preemraff Lysekil on the Swedish coast, a route outside the Gulf.",
    author: "W.carter",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Product_terminal_at_Preemraff_Lysekil_with_tankers.jpg",
    sourceTitle: "",
  },
  "hormuz-war-risk-insurance-mines-shipping-costs": {
    base: "/img/articles/w/hormuz-war-risk-insurance-mines-shipping-costs",
    srcset: "/img/articles/w/hormuz-war-risk-insurance-mines-shipping-costs-400.jpg 400w, /img/articles/w/hormuz-war-risk-insurance-mines-shipping-costs-800.jpg 800w, /img/articles/w/hormuz-war-risk-insurance-mines-shipping-costs-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "A naval moored mine, the hazard insurers priced into Gulf transits.",
    alt: "A naval moored mine, the hazard insurers priced into Gulf transits.",
    author: "John Seb Barber from Leeds, UK",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Hornmine_i_Churchillparken.jpg",
    sourceTitle: "",
  },
  "qatari-lng-tanker-struck-strait-hormuz-august": {
    base: "/img/articles/w/qatari-lng-tanker-struck-strait-hormuz-august",
    srcset: "/img/articles/w/qatari-lng-tanker-struck-strait-hormuz-august-400.jpg 400w, /img/articles/w/qatari-lng-tanker-struck-strait-hormuz-august-800.jpg 800w, /img/articles/w/qatari-lng-tanker-struck-strait-hormuz-august-1400.jpg 1400w",
    width: 1400,
    height: 788,
    caption: "An LNG carrier under way. Qatar's LNG exports leave through the Gulf.",
    alt: "An LNG carrier under way. Qatar's LNG exports leave through the Gulf.",
    author: "JoachimKohlerBremen",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/LNG_Tanker_ARCTIC_PRINCESS_vor_Hammerfest_(N)_-_Juni_2015.jpg",
    sourceTitle: "",
  },
  "dry-bulk-ship-struck-hormuz-crew-abandon-vessel": {
    base: "/img/articles/w/dry-bulk-ship-struck-hormuz-crew-abandon-vessel",
    srcset: "/img/articles/w/dry-bulk-ship-struck-hormuz-crew-abandon-vessel-400.jpg 400w, /img/articles/w/dry-bulk-ship-struck-hormuz-crew-abandon-vessel-800.jpg 800w, /img/articles/w/dry-bulk-ship-struck-hormuz-crew-abandon-vessel-1400.jpg 1400w",
    width: 1400,
    height: 933,
    caption: "A bulk carrier at a Russian port, the ship class abandoned in the August incident.",
    alt: "A bulk carrier at a Russian port, the ship class abandoned in the August incident.",
    author: "Alexxx1979",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Feodosiya_port_Bulk_carrier_Era_IMG_3090_1725.jpg",
    sourceTitle: "",
  },
  "israel-seizes-beaufort-castle-deepest-lebanon-incursion": {
    base: "/img/articles/w/israel-seizes-beaufort-castle-deepest-lebanon-incursion",
    srcset: "/img/articles/w/israel-seizes-beaufort-castle-deepest-lebanon-incursion-400.jpg 400w, /img/articles/w/israel-seizes-beaufort-castle-deepest-lebanon-incursion-800.jpg 800w, /img/articles/w/israel-seizes-beaufort-castle-deepest-lebanon-incursion-1400.jpg 1400w",
    width: 1400,
    height: 977,
    caption: "Beaufort Castle in southern Lebanon.",
    alt: "Beaufort Castle in southern Lebanon.",
    author: "david55king",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Beaufort1982.jpg",
    sourceTitle: "",
  },
  "israel-us-strikes-iran-oil-market-february-2026": {
    base: "/img/articles/w/israel-us-strikes-iran-oil-market-february-2026",
    srcset: "/img/articles/w/israel-us-strikes-iran-oil-market-february-2026-400.jpg 400w, /img/articles/w/israel-us-strikes-iran-oil-market-february-2026-800.jpg 800w",
    width: 800,
    height: 1140,
    caption: "An Iranian oil refinery at night, the facility class the strikes targeted.",
    alt: "An Iranian oil refinery at night, the facility class the strikes targeted.",
    author: "Author's name excised",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/The_Battle_for_Iran_-_2014_release_-_Appendixes.pdf",
    sourceTitle: "",
  },
  "uae-intercepts-two-iranian-ballistic-missiles-august": {
    base: "/img/articles/w/uae-intercepts-two-iranian-ballistic-missiles-august",
    srcset: "/img/articles/w/uae-intercepts-two-iranian-ballistic-missiles-august-400.jpg 400w, /img/articles/w/uae-intercepts-two-iranian-ballistic-missiles-august-800.jpg 800w, /img/articles/w/uae-intercepts-two-iranian-ballistic-missiles-august-1400.jpg 1400w",
    width: 1400,
    height: 1750,
    caption: "An interceptor launch. The UAE said it intercepted two ballistic missiles.",
    alt: "An interceptor launch. The UAE said it intercepted two ballistic missiles.",
    author: "Photographer's name not specified",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Arrow_anti-ballistic_missile_launch.jpg",
    sourceTitle: "",
  },
  "why-indian-pilots-want-gulf-flights-suspended": {
    base: "/img/articles/w/why-indian-pilots-want-gulf-flights-suspended",
    srcset: "/img/articles/w/why-indian-pilots-want-gulf-flights-suspended-400.jpg 400w, /img/articles/w/why-indian-pilots-want-gulf-flights-suspended-800.jpg 800w, /img/articles/w/why-indian-pilots-want-gulf-flights-suspended-1400.jpg 1400w",
    width: 1400,
    height: 934,
    caption: "An Air India Boeing 777-300ER, the type flown on Gulf services.",
    alt: "An Air India Boeing 777-300ER, the type flown on Gulf services.",
    author: "Eluveitie",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Boeing_777-337ER_-_Air_India_(VT-ALK).JPG",
    sourceTitle: "",
  },
  "after-the-tariff-ruling-washingtons-150-day-clock-is-running": {
    base: "/img/articles/w/after-the-tariff-ruling-washingtons-150-day-clock-is-running",
    srcset: "/img/articles/w/after-the-tariff-ruling-washingtons-150-day-clock-is-running-400.jpg 400w, /img/articles/w/after-the-tariff-ruling-washingtons-150-day-clock-is-running-800.jpg 800w, /img/articles/w/after-the-tariff-ruling-washingtons-150-day-clock-is-running-1400.jpg 1400w",
    width: 1400,
    height: 1560,
    caption: "The dome of the United States Capitol, where the tariff clock was set running.",
    alt: "The dome of the United States Capitol, where the tariff clock was set running.",
    author: "Diliff",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/US_Capitol_dome_Jan_2006.jpg",
    sourceTitle: "",
  },
  "india-us-trade-framework-tariff-cuts-february-2026": {
    base: "/img/articles/w/india-us-trade-framework-tariff-cuts-february-2026",
    srcset: "/img/articles/w/india-us-trade-framework-tariff-cuts-february-2026-400.jpg 400w, /img/articles/w/india-us-trade-framework-tariff-cuts-february-2026-800.jpg 800w, /img/articles/w/india-us-trade-framework-tariff-cuts-february-2026-1400.jpg 1400w",
    width: 1400,
    height: 1560,
    caption: "The United States Capitol.",
    alt: "The United States Capitol.",
    author: "Diliff",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    sourceUrl: "https://commons.wikimedia.org/wiki/US_Capitol_dome_Jan_2006.jpg",
    sourceTitle: "",
  },
  "oil-crude-plunges-after-two-week-us-iran-ceasefire": {
    base: "/img/articles/w/oil-crude-plunges-after-two-week-us-iran-ceasefire",
    srcset: "/img/articles/w/oil-crude-plunges-after-two-week-us-iran-ceasefire-400.jpg 400w, /img/articles/w/oil-crude-plunges-after-two-week-us-iran-ceasefire-800.jpg 800w, /img/articles/w/oil-crude-plunges-after-two-week-us-iran-ceasefire-1400.jpg 1400w",
    width: 1400,
    height: 917,
    caption: "The long history of crude oil prices since 1861, the series the fall was measured against.",
    alt: "The long history of crude oil prices since 1861, the series the fall was measured against.",
    author: "Jashuah",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Crude_oil_prices_since_1861.png",
    sourceTitle: "",
  },
  "hungary-election-2026-tisza-wins-orbans-concession": {
    base: "/img/articles/w/hungary-election-2026-tisza-wins-orbans-concession",
    srcset: "/img/articles/w/hungary-election-2026-tisza-wins-orbans-concession-400.jpg 400w, /img/articles/w/hungary-election-2026-tisza-wins-orbans-concession-800.jpg 800w, /img/articles/w/hungary-election-2026-tisza-wins-orbans-concession-1400.jpg 1400w",
    width: 1400,
    height: 855,
    caption: "The Hungarian Parliament in Budapest.",
    alt: "The Hungarian Parliament in Budapest.",
    author: "Dirk Beyer",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/Budapest_Parliament_4604.JPG",
    sourceTitle: "",
  },
  "ipl-2026-final-rcb-beat-gujarat-titans": {
    base: "/img/articles/w/ipl-2026-final-rcb-beat-gujarat-titans",
    srcset: "/img/articles/w/ipl-2026-final-rcb-beat-gujarat-titans-400.jpg 400w, /img/articles/w/ipl-2026-final-rcb-beat-gujarat-titans-800.jpg 800w, /img/articles/w/ipl-2026-final-rcb-beat-gujarat-titans-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "M. Chinnaswamy Stadium in Bengaluru, venue of the IPL final.",
    alt: "M. Chinnaswamy Stadium in Bengaluru, venue of the IPL final.",
    author: "Schumrossi",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Chinnaswamy_stadium.jpg",
    sourceTitle: "",
  },
  "ipl-2026-opener-rcb-srh-bengaluru-empty-seats": {
    base: "/img/articles/w/ipl-2026-opener-rcb-srh-bengaluru-empty-seats",
    srcset: "/img/articles/w/ipl-2026-opener-rcb-srh-bengaluru-empty-seats-400.jpg 400w, /img/articles/w/ipl-2026-opener-rcb-srh-bengaluru-empty-seats-800.jpg 800w, /img/articles/w/ipl-2026-opener-rcb-srh-bengaluru-empty-seats-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "M. Chinnaswamy Stadium, where the opener was played.",
    alt: "M. Chinnaswamy Stadium, where the opener was played.",
    author: "Schumrossi",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Chinnaswamy_stadium.jpg",
    sourceTitle: "",
  },
  "india-women-australia-odi-t20i-squads-january-2026": {
    base: "/img/articles/w/india-women-australia-odi-t20i-squads-january-2026",
    srcset: "/img/articles/w/india-women-australia-odi-t20i-squads-january-2026-400.jpg 400w, /img/articles/w/india-women-australia-odi-t20i-squads-january-2026-800.jpg 800w, /img/articles/w/india-women-australia-odi-t20i-squads-january-2026-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "Wankhede Stadium in Mumbai.",
    alt: "Wankhede Stadium in Mumbai.",
    author: "Sports Fan",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Wankhede-1.JPG",
    sourceTitle: "",
  },
  "india-thrash-afghanistan-by-innings-and-300-runs": {
    base: "/img/articles/w/india-thrash-afghanistan-by-innings-and-300-runs",
    srcset: "/img/articles/w/india-thrash-afghanistan-by-innings-and-300-runs-400.jpg 400w, /img/articles/w/india-thrash-afghanistan-by-innings-and-300-runs-800.jpg 800w, /img/articles/w/india-thrash-afghanistan-by-innings-and-300-runs-1400.jpg 1400w",
    width: 1400,
    height: 428,
    caption: "Eden Gardens in Kolkata.",
    alt: "Eden Gardens in Kolkata.",
    author: "Partha Bhaumik",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Eden_Gardens_Kolkata.jpg",
    sourceTitle: "",
  },
  "mirabai-chanu-to-carry-india-flag-at-glasgow": {
    base: "/img/articles/w/mirabai-chanu-to-carry-india-flag-at-glasgow",
    srcset: "/img/articles/w/mirabai-chanu-to-carry-india-flag-at-glasgow-400.jpg 400w, /img/articles/w/mirabai-chanu-to-carry-india-flag-at-glasgow-800.jpg 800w, /img/articles/w/mirabai-chanu-to-carry-india-flag-at-glasgow-1400.jpg 1400w",
    width: 1400,
    height: 2070,
    caption: "A weightlifting platform at a competition.",
    alt: "A weightlifting platform at a competition.",
    author: "Government of Indonesia",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/1968_Mexico_Olympics%2C_5rp_(1968).jpg",
    sourceTitle: "",
  },
  "supreme-court-ieepa-tariff-ruling-what-changed": {
    base: "/img/articles/w/supreme-court-ieepa-tariff-ruling-what-changed",
    srcset: "/img/articles/w/supreme-court-ieepa-tariff-ruling-what-changed-400.jpg 400w, /img/articles/w/supreme-court-ieepa-tariff-ruling-what-changed-800.jpg 800w, /img/articles/w/supreme-court-ieepa-tariff-ruling-what-changed-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "The Supreme Court of the United States, which ruled on the emergency tariff authority.",
    alt: "The Supreme Court of the United States, which ruled on the emergency tariff authority.",
    author: "Photo by Mr. Kjetil Ree .",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/US_Supreme_Court.JPG",
    sourceTitle: "",
  },
  "us-supreme-court-climate-suits-big-oil-request-explainer": {
    base: "/img/articles/w/us-supreme-court-climate-suits-big-oil-request-explainer",
    srcset: "/img/articles/w/us-supreme-court-climate-suits-big-oil-request-explainer-400.jpg 400w, /img/articles/w/us-supreme-court-climate-suits-big-oil-request-explainer-800.jpg 800w, /img/articles/w/us-supreme-court-climate-suits-big-oil-request-explainer-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "The Supreme Court of the United States, whose new term opened with the climate application.",
    alt: "The Supreme Court of the United States, whose new term opened with the climate application.",
    author: "Photo by Mr. Kjetil Ree .",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/US_Supreme_Court.JPG",
    sourceTitle: "",
  },
  "europe-summer-heat-stress-glacier-loss": {
    base: "/img/articles/w/europe-summer-heat-stress-glacier-loss",
    srcset: "/img/articles/w/europe-summer-heat-stress-glacier-loss-400.jpg 400w, /img/articles/w/europe-summer-heat-stress-glacier-loss-800.jpg 800w, /img/articles/w/europe-summer-heat-stress-glacier-loss-1400.jpg 1400w",
    width: 1400,
    height: 1867,
    caption: "The Mer de Glacier on Mont Blanc, one of the Alpine glaciers cited in the heat-stress reporting.",
    alt: "The Mer de Glacier on Mont Blanc, one of the Alpine glaciers cited in the heat-stress reporting.",
    author: "Tangopaso",
    license: "Public domain",
    licenseUrl: "",
    sourceUrl: "https://commons.wikimedia.org/wiki/Glacier_des_Bossons_from_le_Brevent.jpg",
    sourceTitle: "",
  },
  "indian-open-42km-race-walk-baboo-rani": {
    base: "/img/articles/w/indian-open-42km-race-walk-baboo-rani",
    srcset: "/img/articles/w/indian-open-42km-race-walk-baboo-rani-400.jpg 400w, /img/articles/w/indian-open-42km-race-walk-baboo-rani-800.jpg 800w, /img/articles/w/indian-open-42km-race-walk-baboo-rani-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "Race walking at a championships, the discipline the 42km addition returned to the Indian Open.",
    alt: "Race walking at a championships, the discipline the 42km addition returned to the Indian Open.",
    author: "Bearas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/20260815_2026_European_Athletics_Championships_%E2%80%93_Race_walking_08.jpg",
    sourceTitle: "",
  },
  "paris-fashion-week-afghan-designs-valentino": {
    base: "/img/articles/w/paris-fashion-week-afghan-designs-valentino",
    srcset: "/img/articles/w/paris-fashion-week-afghan-designs-valentino-400.jpg 400w, /img/articles/w/paris-fashion-week-afghan-designs-valentino-800.jpg 800w, /img/articles/w/paris-fashion-week-afghan-designs-valentino-1400.jpg 1400w",
    width: 1400,
    height: 1050,
    caption: "The Palais de Tokyo, a Paris fashion week venue.",
    alt: "The Palais de Tokyo, a Paris fashion week venue.",
    author: "Strobilomyces",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Palais_de_Tokyo_20030101w.JPG",
    sourceTitle: "",
  },
  "tamil-writer-poomani-dies-at-79": {
    base: "/img/articles/w/tamil-writer-poomani-dies-at-79",
    srcset: "/img/articles/w/tamil-writer-poomani-dies-at-79-400.jpg 400w, /img/articles/w/tamil-writer-poomani-dies-at-79-800.jpg 800w, /img/articles/w/tamil-writer-poomani-dies-at-79-1400.jpg 1400w",
    width: 1400,
    height: 937,
    caption: "A memorial to Tamil writing in Jaffna.",
    alt: "A memorial to Tamil writing in Jaffna.",
    author: "Jbuchholz",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/Jaffna_Tamil_Conference_memorial_detail.JPG",
    sourceTitle: "",
  },
};
